### ISSUE TITLE
Test and update macOS font statuses

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#123] opened 2016-12-27 21:18 UTC
#### Test and update macOS font statuses

For each font:
* test the complete version of the font on macOS
  * installs, no severe messages from font book
* update the appropriate font in the readme table "Patched Fonts" > "Status" column
  * table location: https://github.com/ryanoasis/nerd-fonts#patched-fonts
  * use the already provided img reference links at the bottom of the readme

**Comment by No0n3Left** [comment] 2017-06-25 20:50
`Knack Bold Italic Nerd Font Complete Mono.ttf` and `Knack Bold Italic Nerd Font Complete.ttf` give two minor warnings when you import them with font book. Each warns the name table is unusable, showing the following errors: 
<img width="1278" alt="knackbierror1" src="https://user-images.githubusercontent.com/25831613/27519622-6036e92a-59bd-11e7-90b2-2d9c9b641e4b.png">
<img width="1275" alt="knackbierror2" src="https://user-images.githubusercontent.com/25831613/27519623-60370ef0-59bd-11e7-91dc-0aaf9dcc29ce.png">
Other than that it works if you just ignore the erorrs and install them anyways.

**Comment by ryanoasis** [comment] 2017-07-01 02:38
@No0n3Left Thanks for the details here :smile: 

I wonder if you get the same warnings if you install only one or the other and not both (only mono or only non-mono version of the font) ?

**Comment by hackrush01** [comment] 2019-05-13 05:19
Hey, @ryanoasis was the cause of this problem found? I'm only installing the non-mono version and I'm still seeing it.

**Comment by Finii** [comment] 2023-01-30 11:36
The problem is knows and can be solved by patching with `--makegroups`. `v3.0.0` will do so with all fonts, but the names will change then (slightly).

Adding this to future and closing.

**Closed by Finii** 2023-01-30 11:36 UTC
Labels: help wanted, os:osx, Hacktoberfest, 24PullRequests, up-for-grabs
