### ISSUE TITLE
Wrong fl, ff, ffi and fi using Nerd Fonts Noto Sans Mono

### ISSUE THREAD

**Issue by medmedin2014** [ryanoasis/nerd-fonts#879] opened 2022-08-17 15:58 UTC
![Screenshot_20220817_165529-1](https://user-images.githubusercontent.com/7027319/185186880-ea2fc640-1be5-411d-835d-26bcd9190c12.png)

**Comment by Finii** [comment] 2022-08-18 08:13
Duplicate of #477 #254
Fixed in #711

@medmedin2014 There is no 'real' fixed release yet, just take the [`v2.2.0 RC`](https://github.com/ryanoasis/nerd-fonts/releases/tag/2.2.0-RC)

**Closed by Finii** 2022-08-18 08:13 UTC
Labels: ♒ duplicate
