### ISSUE TITLE
Font parcher - fonts get blurred/grayed out

### ISSUE THREAD

**Issue by im-n1** [ryanoasis/nerd-fonts#329] opened 2019-02-26 11:13 UTC
Hi folks

I've spend many hours choosing my new font to substidue my bitmap current one (need scalability). The major thing bitmap fonts are so great (according to me) is they are sharp and thus well visible. I could achieve the same visibility and sharpness with AnonymousPro font. But if I try to use your patched font or i do patch it by myself with your font patcher I get blurry font and grayed out characters.

Before patching
![image](https://user-images.githubusercontent.com/198654/53408704-766e7d00-39bf-11e9-8cf6-bb9aa90777a0.png)

After
![image](https://user-images.githubusercontent.com/198654/53408725-84bc9900-39bf-11e9-9044-85d1b2443352.png)

The letter spacing is ok - i can adjust that in Xresources. But not the blurriness :(

**Comment by gim913** [comment] 2019-02-28 09:23
There's actually same issue with `Terminess TTF Nerd` font

This is Terminus TTF font:
![image](https://user-images.githubusercontent.com/496298/53555718-c45fbe00-3b42-11e9-996d-4d6ec9c47657.png)


This is Terminess TTF Nerd from patched-fonts dir:
![image](https://user-images.githubusercontent.com/496298/53555765-de010580-3b42-11e9-887a-5dfe3f7f4639.png)

**Comment by im-n1** [comment] 2019-03-02 12:39
Offtopic: whats the crate you are working on?

**Comment by gim913** [comment] 2019-03-02 17:11
> Offtopic: whats the crate you are working on?

actually not my crate, clone of https://github.com/Peltoche/lsd
(apparently github needs some kind of chat/messaging ^^)

**Comment by im-n1** [comment] 2019-03-02 18:14
Nice to see another Rust dev. Let's use irc. Serv: irc.mozilla.org, chann: rust

Back to topic:
The `lsd` is nice tool. Another usage for nerd fonts. I hope the font patcher will be fixed soon.

**Comment by Slabity** [comment] 2019-12-30 15:46
Anything on this?

Bitmap fonts are still blurry when patched. What seems to be the issue?

**Comment by im-n1** [comment] 2019-12-31 08:33
I just tried already patched font in term Alacritty and it's completely different font...

**Comment by Slabity** [comment] 2020-11-04 18:56
Bumping... Still broken...

**Comment by pinusc** [comment] 2020-11-16 21:10
I believe there is a chance this is related to fontconfig issues. I have been playing with my configuration all day, and can not seem to achieve the same sharpness as when using .pcf or .otb fonts (testing on GohuFont)
I can achieve sharpness by disabling antialiasing, but then the font "breaks", I suspect as a result of hinting.

**Comment by topaxi** [comment] 2021-06-03 15:04
This is not only happening with bitmap fonts but any font :confused:

**Comment by Akselmo** [comment] 2021-11-04 11:25
Ive seen this problem too. I really like the terminus font in its bitmap form

**Comment by gim913** [comment] 2021-11-05 08:30
> Ive seen this problem too. I really like the terminus font in its bitmap form

And so I've switched to Iosevka ¯\_(ツ)_/¯
https://github.com/be5invis/Iosevka

**Comment by yamabiiko** [comment] 2022-02-08 23:46
Is there any update on this? Terminess Nerd Font still looks blurry in my system

**Comment by Finii** [comment] 2022-02-09 11:58
I looked a bit into this.

Terminus is a bitmap only font http://terminus-font.sourceforge.net/
> Q. Scalable version?
> A. Long story short, when the average display resolution becomes at least 150 DPI. Prefferably 200.

The bitmap fonts are bundled into a `ttf` then with https://github.com/Tblue/mkttf
to form the `Terminus (TTF)` we use as base.

_(Well in fact in the middle this is also involved: https://github.com/drew-kun/terminus_powerline_font_osx, I guess. Or something alike there are multiple projects; but that has no influence on the technical aspect in this comment)_

That `mkttf` takes all bitmap fonts, stuffs them into a `ttf` file and uses `autotrace` or `potrace` to create **also** a scalable font.
I see no special handling in the `potrace` call, and I also see no manual adjustments to the resultant glyphs we use (like `Almost Vertical` etc). So the results are ... sorry, I would call that mediocre.

![image](https://user-images.githubusercontent.com/16012374/153193402-03016177-a1b5-4e78-b8a4-8556765b72bc.png)

If you use the 'original' TTF (calling it 'original' feels a bit strange) you in fact use the embedded bitmap fonts (I believe). Thus the result looks good. After Nerd Font patching the bitmaps are dropped (we do not patch bitmaps), and the (mediocre) outlines are used.

Making good outlines for Terminus would involve a lot of work, also manually. This is nothing I would conduct.

So sorry, I see no easy solution for this. But maybe I'm wrong. @ryanoasis might know more about Terminus.
More info maybe at Issue #23

**Comment by Finii** [comment] 2022-02-09 12:36
Duplicate of #86

**Comment by DoctorKnowsBetter** [comment] 2022-09-22 21:47
I fixed this crap :)
[https://github.com/DoctorKnowsBetter/TerminessNerdFont-FixBlur](url)

**Comment by Finii** [comment] 2022-09-24 09:42
Closed via #939.

Many thanks to @DoctorKnowsBetter for finding a solution and help testing!

**Closed by Finii** 2022-09-24 09:42 UTC
