### ISSUE TITLE
Have the fonts had their monospaced flag omitted?

### ISSUE THREAD

**Issue by redactedscribe** [ryanoasis/nerd-fonts#909] opened 2022-09-02 18:47 UTC
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
A program I use called Directory Opus limits the selection of selectable fonts to those that have been marked or flagged in some way as being true monospaced fonts. With the NF 2.1.0 release of 2020, the program could see the Nerd Fonts in its list, but there was a problem with them being displayed if the non- "mono" suffixed Nerd Fonts of the same name were installed too. Previously, I just uninstalled all fonts and then installed only the "mono" suffixed fonts and the problem was solved, but now with 2.2.1, it doesn't matter if the "mono" suffixed fonts are the only ones installed, Directory Opus is unable to see them. The program can see the fonts when it's not limiting the font list to true monospaced fonts, but whatever method it was using to detect the flag doesn't work for 2.2.1 as far as I can tell. I assume something has changed regarding the Nerd Fonts' monospaced flags and not Directory Opus.

#### 🔧 Your Setup

- Mononoki NF Mono, Liberationmono NF Mono, Hack NF Mono, and others: All cannot be seen by Directory Opus when searching for "real" monospaced fonts.
   - Full filename: Whatever the NF Scoop bucket below is fetching.
   - Source: NF Scoop bucket ([example manifest](https://github.com/matthewjberger/scoop-nerd-fonts/blob/master/bucket/Mononoki-NF-Mono.json)).
- Directory Opus 12.29
- Windows 11

#### ★ Screenshots (Optional)

Installed NF fonts according to Windows:

![ApplicationFrameHost_2022-09-02_21-39-57](https://user-images.githubusercontent.com/25013746/188217426-1c7e6a19-15a7-4997-912c-7ada10b76807.png)

Fonts absent from Directory Opus' monospaced fonts list:

![dopus_2022-09-02_21-38-16](https://user-images.githubusercontent.com/25013746/188217184-9110888d-1317-4054-b26f-8968379f5f80.png)

The Directory Opus developers have also been notified about the issue.

Thanks.

**Comment by Finii** [comment] 2022-09-02 19:26
Do you by chance know if there is a test version or test periode for Opus? So that I could reproduce...

Can you check Caskaydia Cove? Because it is handled a bit differently.

Do you install all fonts? Like Nerd Fond and Nerd Font Mono and the two Windows Compat ones?

**Comment by Finii** [comment] 2022-09-02 19:29
Literation looks bad :-o

Is that really 2.1.1 and rebooted after update?

Sorry Im not on Windows normally, so no quick check.

**Comment by redactedscribe** [comment] 2022-09-02 21:14
> Do you by chance know if there is a test version or test periode for Opus? So that I could reproduce...

60 day free evaluation: https://www.gpsoft.com.au/

> Can you check Caskaydia Cove? Because it is handled a bit differently.

I will have to try this tomorrow.

> Do you install all fonts? Like Nerd Fond and Nerd Font Mono and the two Windows Compat ones?

I've installed both options that the [NF Scoop bucket](https://github.com/matthewjberger/scoop-nerd-fonts/tree/master/bucket) provides, e.g. for Mononoki: [Mononoki-NF-Mono.json](https://github.com/matthewjberger/scoop-nerd-fonts/blob/master/bucket/Mononoki-NF-Mono.json) and [Mononoki-NF.json](https://github.com/matthewjberger/scoop-nerd-fonts/blob/master/bucket/Mononoki-NF.json). I've tried uninstalling _all_ NF fonts and only installing the "Mono" versions via Scoop, but that didn't do the trick (which is what worked for me last year to get Opus to see the monospaced fonts, at least, that seemed to be what I did right). I've tried numerous times, uninstalling, reinstalling, rebooting between each step, and Opus won't see them on my system, that is, specifically in its monospaced-only fonts lists.

> Literation looks bad :-o Is that really 2.1.1 and rebooted after update?

I assume Literation is the same as Li*ber*ation: There is no Literatin*Sans* manifest so I assume it was installed via one of the LiterationMono manifests: [Mono](https://github.com/matthewjberger/scoop-nerd-fonts/blob/master/bucket/LiberationMono-NF-Mono.json), [Non-mono](https://github.com/matthewjberger/scoop-nerd-fonts/blob/master/bucket/LiberationMono-NF.json). Using "LiterationSans NF" as a font in VS Code does show that the font is double wide.

![Fonts 2022-09-03_00-13-27](https://user-images.githubusercontent.com/25013746/188236177-5aa354d6-d2b2-4aa4-bb20-755749f6c0e6.png)

**Comment by Finii** [comment] 2022-09-03 06:58
Good information, will check that all out, thanks!

**Comment by jgeorge300** [comment] 2022-09-04 13:12
I believe I'm seeing this issue on macOS with the JetBrains fonts as well. In Terminal.app, you can see a change in which fonts are listed under the "Fixed Width" filter under Profiles -> Fonts. Prior to 2.2.1, the JetBrains mono font was listed. Now it is not.

**Comment by Finii** [comment] 2022-09-04 14:47
I believe one problem is that the Family names are wrong after patching, at least for the `Windows Compatible` versions.

This is hard to read, but anyhow. Here we see just the 'JetBrainsMono Ligatures Nerd Font Regular'. This includes 4 variants, 'Nerd Font non-Mono` and `Nerd Font Mono` and `Windows Compat` - you know what I mean:

![image](https://user-images.githubusercontent.com/16012374/188319192-b9c32ca6-b691-4569-991d-891c42bc92d9.png)

Have a close look at the Family name. For both `Windows Compatible` versions (i.e. `Nerd Font` and `Nerd Font Mono`) the Family is `JetBrainsMono NF`. That means that both, the mono and the non-mono font are in the same Family and so the whole Family is not Monospaced anymore.

Do you see the problem also in the non-Windows-Compat fonts? @jgeorge300 on Mac I assume you do not use the Windows Compat fonts?

And still the question... is the problem als existing in `CaskaydiaCove Nerd Font Mono`? Because that font uses a new algorithm to set the Family names...

**Comment by redactedscribe** [comment] 2022-09-04 16:42
> Have a close look at the Family name. For both `Windows Compatible` versions (i.e. `Nerd Font` and `Nerd Font Mono`) the Family is `JetBrainsMono NF`. That means that both, the mono and the non-mono font are in the same Family and so the whole Family is not Monospaced anymore.

I think I do recall seeing two distinct fonts families (mono and non-mono) listed per NF font in the Windows Fonts settings window before the last two release, so it sounds like this could be the issue. Should the fix be relatively easy then?

**Comment by Finii** [comment] 2022-09-04 16:56
Another problem is that the `Mono` font is not strictly monospaced... (600 vs 612)

![image](https://user-images.githubusercontent.com/16012374/188324556-d4f1eb84-5df0-4f1f-84c4-5c1eee680ec2.png)

@redactedscribe that is all relatively easy to fix, and all solutions are already implemented as PRs.

So the Family naming would be fixed if `--makegroups` is added to the patching command line or font specific font file.

The monospace-iety would be fixed by #764, but that needs a lot of consideration (#900)

It would be quite helpful if you could just look Caskaydia Cove up.
I'm still without machine to test anything, and tomorrow is already completely full with day-job work :-(

**Comment by redactedscribe** [comment] 2022-09-04 17:57
> that is all relatively easy to fix, and all solutions are already implemented as PRs.

If I've understood you correctly, the wait may be long.

> It would be quite helpful if you could just look Caskaydia Cove up.

I just installed [CascadiaCode-NF-Mono.json](https://github.com/matthewjberger/scoop-nerd-fonts/blob/master/bucket/CascadiaCode-NF-Mono.json) and (without restarting) I looked at Directory Opus those NF mono fonts are displaying in the monospaced fonts only list. I guess that new algorithm works.

![dopus_2022-09-04_20-53-41](https://user-images.githubusercontent.com/25013746/188326982-c8d3eba9-eb34-442f-bd1f-3aa427f1cc79.png)

**Comment by jgeorge300** [comment] 2022-09-04 18:14
Correct. I'm not using the Windows compat versions. I was able to upgrade the Caskaydia Cove fonts on macOS from 2.1.0 to 2.2.1 and see the same issue as I'm seeing with Jetbrains font.

**Comment by Finii** [comment] 2022-09-04 18:25
Thank you both.

> If I've understood you correctly, the wait may be long.

Depending on my day work workload I hope for another bugfix release within September. (Of year 2022 ;-> )

**Comment by Finii** [comment] 2022-09-06 08:15
Opus seems to be fixed after
* #764

which I more and more believe is the way to go (#325 

I have no Mac (well I have a mac build machine, but just `ssh` access so can not 'see'), someone willing to test it on mac?

![image](https://user-images.githubusercontent.com/16012374/188582490-fcddb0a4-952f-47b3-92a6-43483352353d.png)

**Comment by redactedscribe** [comment] 2022-09-06 10:35
> I have no Mac (well I have a mac build machine, but just ssh access so can not 'see'), someone willing to test it on mac?

Maybe @jgeorge300 would be able to take a look.

**Comment by jgeorge300** [comment] 2022-09-06 13:36
@Finii I can test. I normally install my fonts via Home-brew. Can you point me to the version of the fonts that I can test manually.

**Comment by Finii** [comment] 2022-09-06 14:07
Ah great. If you can test and it is 'good' we can release a new bugfix version 2.2.2.

The patching (via CI) is running here: https://github.com/Finii/nerd-fonts/actions/runs/3000805081

I will point you to the resultant archive (which you have to manually install, all individual font files), once it finishes, which is in about 20 minutes?

**Comment by Finii** [comment] 2022-09-06 14:13
> in about 20 minutes?

I broke something :->

**Comment by jgeorge300** [comment] 2022-09-06 16:19
@Finii I've manually installed the two non windows fonts from [JetBrainsMono](https://github.com/Finii/nerd-fonts/tree/v2.2.2-RC/patched-fonts/JetBrainsMono/NoLigatures/Regular/complete).

The macOS Font Book now shows the fonts correctly. My broken app is now able to see the font as well. Terminal.app also lists it under fixed width fonts as well.

<img width="1582" alt="fixedwidth" src="https://user-images.githubusercontent.com/513514/18868
<img width="1582" alt="full" src="https://user-images.githubusercontent.com/513514/188685756-e6cc7d6f-6a43-424e-93ee-aaed4ef24f45.png">
5731-6a4f8909-51f0-4e25-8c7f-8bdd4e1b627d.png">

**Comment by Finii** [comment] 2022-09-06 16:37
> @Finii I've manually installed the two non windows fonts from...

Thank you for testing!

**Comment by redactedscribe** [comment] 2022-09-06 18:00
Since the previous test was for a NoLigatures on Mac, I tried "JetBrains Mono Regular Nerd Font Complete Mono Windows Compatible.ttf" from JetBrainsMono/**Ligatures**/Regular/complete on Windows. After installing it, it showed up in Directory Opus immediately:

![font shown](https://user-images.githubusercontent.com/25013746/188706457-9f881000-60d4-426a-885f-2344549b621e.png)

**Comment by Finii** [comment] 2022-09-06 18:11
Thanks to you also for testing :-)

> another bugfix release within September

Looks like real soon now ;-)

**Closed** 2022-09-07 06:03 UTC
Labels: confirmed

**Comment by sarim** [comment] 2022-09-17 17:35
Is this issue solved? I downloaded [v2.2.2](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.2.2) but `CaskaydiaCove NF Mono` isn't really mono, it still renders ligatures.

**Comment by Finii** [comment] 2022-09-18 05:18
> `CaskaydiaCove NF Mono` isn't really mono, it still renders ligatures

It is monospaced **and** has ligatures. Being monospaced has something to do with the cell width for each character, not if two consecutive characters are rendered differently (in their respective) cells.

Nerd Font 'in general' does not tough ligatures; there are exceptions and misleading information about this in the documentation.

What you probably want is `CaskaydiaMono NF Mono`?
Or just turn ligature rendering off in your client? Most clients that know ligatures and do render them can be told to not do that.

`CaskaydiaMono` (from `Cascadia Mono`) is not prepatched for the Nerd Fonts release and you have to patch it yourself. Self patching is not very hard, if you need help with that.

(Or maybe use `Delugia Mono` from another project.)

**Comment by Finii** [comment] 2022-09-18 05:25
How to turn off ligatures in `Windows Terminal` (result of a quick search, I do not use it):
https://github.com/microsoft/terminal/issues/759#issuecomment-931743104

**Comment by Finii** [comment] 2022-09-18 05:30
@sarim see also https://github.com/ryanoasis/nerd-fonts/issues/520#issuecomment-1007228119

**Comment by sarim** [comment] 2022-09-18 15:45
> Nerd Font 'in general' does not tough ligatures; there are exceptions and misleading information about this in the documentation.

Yeah, I don't know much about how fonts work, I googled "nerd font without ligatures" and got this 

https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraCode/font-info.md#ligatures
> By the Nerd Font policy, the variant with the 'Mono' suffix is not supposed to have any ligatures. Use the non-Mono variants to have ligatures.



> How to turn off ligatures in `Windows Terminal` (result of a quick search, I do not use it):

Yeah, it worked. That was the easiest solution. Thanks :)
