### ISSUE TITLE
Add devicon fonts (different from deviconS)

### ISSUE THREAD

**Issue by jmigual** [ryanoasis/nerd-fonts#1112] opened 2023-02-09 10:16 UTC
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
I'd like to have the CMake icon in my terminal. Specially to replace the triangle in the starship [CMake](https://starship.rs/config/#cmake) module. 

**Describe the solution you'd like**
I can use the CMake icon in my shell.

**Describe alternatives you've considered**
The alternative would be to patch my own font with my custom glyphs but that's a bit slow because I'll need to do it for every device that I use.

**Additional context**
Right now the devicons used by Nerd Fonts (https://github.com/vorillaz/devicons) are a bit outdated and haven't seen a release in 8 years. I suggest adding the dev icons from https://github.com/devicons/devicon that are regularly updated. Their license is a MIT license so it should be fine.

**Comment by Finii** [comment] 2023-02-09 10:41
Thanks for the idea.
This is a duplicate of
* #615 

thus closing.

There were some problems though, iirc.

Ah, here it is, still unsolved it seems

* https://github.com/devicons/devicon/issues/1420
* https://github.com/devicons/devicon/issues/1516

---

If you are just concerned about the cmake icon, maybe show here how the icon should/will look like.

> patch my own font with my custom glyphs but that's a bit slow because I'll need to do it for every device that I use

You just need to patch it once and then use that font everywhere?

**Closed by Finii** 2023-02-09 10:41 UTC
Labels: ♒ duplicate
