### ISSUE TITLE
fontforge --script ./font-patcher --complete xx.ttf  has error ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by brettKK** [ryanoasis/nerd-fonts#1460] opened 2023-12-18 13:01 UTC
➜  FontPatcher fontforge --script ./font-patcher --complete ./src/glyphs/devicons.ttf
Copyright (c) 2000-2023. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20230101
 Based on sources from 2023-01-01 05:27 UTC-D.
Nerd Fonts Patcher v3.1.1 (4.8.2) (ff 20230101)
Adding 185 Glyphs from Seti-UI + Custom Set
╢████████████████████████████████████████╟ 100%
Adding 6 Glyphs from Heavy Angle Brackets Set
╢████████████████████████████████████████╟ 100%
Adding 198 Glyphs from Devicons Set
╢████████████████████████████████████████╟ 100%
Adding 3 Glyphs from Powerline Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 4 Glyphs from Powerline Symbols Set
╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟ 25%Traceback (most recent call last):
  File "/Users/kk/Downloads/FontPatcher/./font-patcher", line 2072, in <module>
    main()
  File "/Users/kk/Downloads/FontPatcher/./font-patcher", line 2059, in main
    patcher.patch(sourceFonts[-1])
  File "/Users/kk/Downloads/FontPatcher/./font-patcher", line 399, in patch
    self.copy_glyphs(SrcStart, symfont, patch['SymStart'], patch['SymEnd'], patch['Exact'], patch['ScaleRules'], patch['Name'], patch['Attributes'])
  File "/Users/kk/Downloads/FontPatcher/./font-patcher", line 1444, in copy_glyphs
    scale_ratio_x *= 1.0 + (self.font_dim['width'] / (sym_dim['width'] * scale_ratio_x)) * overlap
                            ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero

**Comment by Finii** [comment] 2023-12-18 13:30
Urgh! Sorry to see your problem.
Can you give me a link to the font you want to patch?

**Comment by Finii** [comment] 2023-12-18 13:33
> sichuan university

Ah, most probably a font without latin glyphs, as `font-patcher` detects no source font width.
And there is no code for pure Chinese font's "cell width".

An example font to work with would be good.

**Comment by Finii** [comment] 2023-12-18 14:12
@allcontributors please add @brettKK for bug

**Comment by Finii** [comment] 2023-12-18 14:39
The actual issue (the crash) is fixed via
* #1461

I close this now. If you have information with a only-Chinese-font please reopen and tell me which font it is and we can work out a solution.

The command in the report above is most likely not what was intended.

**Closed as completed by Finii** 2023-12-18 14:39 UTC
Labels: confirmed

**Comment by Finii** [comment] 2023-12-18 14:48
If your intention was to create a font with only all the symbols
* There is special code for the case the to-be-patched font is completely empty (instead of: has some icons)
* Use a really empty font, for example `src/unpatched-fonts/NerdFontsSymbolsOnly/NerdFontsSymbolsNerdFontBlank.sfd`
* Convert from `sfd` to `ttf` with command line parameter `--extension ttf`
* This is how `patched-fonts/NerdFontsSymbolsOnly/SymbolsNerdFont-Regular.ttf` is created
