### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by obxhdx** [ryanoasis/nerd-fonts#8] opened 2015-04-21 21:16 UTC
Hello! I'm trying to patch Inconsolata, but any parameter I give to `font-patcher` causes a seg fault. Below are the package versions I'm using. I'd appreciate if you could tell me if there's anything I'm missing.

```
$ python --version
Python 2.7.9
```

```
$ fontforge --version
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 20:50 BST  1-Apr-2015-D.
 Based on source from git with hash:
fontforge 20:50 BST  1-Apr-2015
libfontforge 20150401
```

```
$ ./font-patcher unpatched-sample-fonts/Inconsolata/Inconsolata\ for\ Powerline.otf
[1]    82858 segmentation fault  ./font-patcher
```

**Comment by ryanoasis** [comment] 2015-04-21 22:20
@obxhdx hmm that is odd. Im using python 2.7.6 though I doubt that is causing anything.

Do you have the python fontforge module? It should be warning about that if not.

Seems like something else is going on...

I have actually been working on running the patcher for the remaining unpatched fonts. I will push it up soon if you want to grab Inconsolata from there

**Comment by obxhdx** [comment] 2015-04-22 01:50
Oh, cool. Thanks for the Inconsolata font!

FYI, I was trying the patcher on a Mac. At first I got the warning about the fontforge module, but installing it via homebrew was enough to get past that.

But well, Inconsolata is all I wanted. Thank you again.

**Comment by adambiggs** [comment] 2015-04-22 18:04
Just ran into this as well... Probably should be reopened.

I'm also using python `2.7.9` and the same version of fontforge, both installed via Homebrew on OSX.

**Comment by ryanoasis** [comment] 2015-04-22 22:27
Hmm probably will need some help on this one.

Did a fresh install of fontforge on Fedora and no issue running the patcher.

If someone could try to debug that'd be great

`python -m pdb ./font-patcher unpatched-sample-fonts/Inconsolata/Inconsolata\ for\ Powerline.otf`
`python -i`

or some other way

initial thoughts... seems like my script is doing something very bad performance wise..

Just out of curiousity, can you tell me what you get for `ulimit -s` ?

Does running the script with the `-q` (quiet) flag make any difference ?

**Comment by nicholasc** [comment] 2015-05-27 19:02
I got the same problem on OS X running Python 2.7.9 and a fontforge build from May 5th. 

I'm not very familiar with Python, but using:
```python -m pdb ./font-patcher unpatched-sample-fonts/Inconsolata/Inconsolata\ for\ Powerline.otf```

I got: 
```> /Users/nicholas/.vim/bundle/nerd-filetype-glyphs-fonts-patcher/font-patcher(3)<module>()
-> import sys
(Pdb) next
> /Users/nicholas/.vim/bundle/nerd-filetype-glyphs-fonts-patcher/font-patcher(4)<module>()
-> import psMat
(Pdb) next
[1]    63258 segmentation fault  python -m pdb ./font-patcher```

Running the script with the quiet flat does not change anything.

It seems like the psMat package might be causing the issue here.

**Comment by nicholasc** [comment] 2015-05-29 13:37
The issue is with fontforge on Mac OS X. I haven't been able to import psMat or fontforge packages in any python script without getting the same segfault. I ended up patching my font on linux.

@ryanoasis I believe this issue can be close on your side as this seems to be a problem related to fontforge. If I ever come across a solution, I'll post it here.

**Comment by ryanoasis** [comment] 2017-08-03 23:22
@nicholasc Thanks! Sorry I never said that!!! :blush: 

I will probably add something to the wiki and close it soon (getting caught up on these issues)

**Comment by ryanoasis** [comment] 2017-08-04 14:40
Closed via: https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting#segmentation-fault-running-python-patcher

**Closed by ryanoasis** 2017-08-04 14:40 UTC
Labels: 24PullRequests, Hacktoberfest, help wanted, os:osx
