### ISSUE TITLE
Wrong letter space after patching Korean font

### ISSUE THREAD

**Issue by dhnam** [ryanoasis/nerd-fonts#522] opened 2020-09-03 08:42 UTC
#### 🎯 Subject of the issue

Patched `D2Coding` font with patcher in Windows 10.
When patched, letter space of Korean charactors are getting weird.
Screenshot is attached in 'optional'.

#### 🔧 Your Setup

- Using `D2Coding` with patcher.
- Now using window CMD, but it is not about patched letters.
- Now using Windows 10, and Nerd Fonts ver. 2.1.0.

#### ★ Optional

![d2-before](https://user-images.githubusercontent.com/8546820/92091515-d2635e80-ee0b-11ea-923d-796338ecb6f7.PNG)
This is what originally looks like;
![d2-after](https://user-images.githubusercontent.com/8546820/92091543-dc855d00-ee0b-11ea-8279-8e07daebb0b9.PNG)
This is how it looks like after patch.
And if I patch it in single-width, it looks like:
![d2-mono](https://user-images.githubusercontent.com/8546820/92092050-895fda00-ee0c-11ea-8f5d-3344eb575e41.PNG)

Not sure it is same with other fullwidth characters(like Chinese or Japanese).

**Comment by dhnam** [comment] 2020-09-04 07:44
Looks like it is own problem of FontForge.
I opened ttf file of D2Coding and directly made font out of it, and it gave me same problem.

**Comment by Finii** [comment] 2023-02-21 14:16
Maybe this can be solved by patching with `--variable-width-glyphs`.
But the patched font then does probably not work in 'all' terminals anymore.

Closing this now. If you still have problems, reopen. I would need a link to the problematic font for testing in that case.

**Comment by kimwonj77** [comment] 2023-04-10 06:58
I have same issue. With same font,  both with/without `--variable-width-glyphs`, both mono and non-mono.
Original font is on https://github.com/naver/d2codingfont/releases/tag/VER1.3.2
Patched font is [without `--variable-width-glyphs`](https://github.com/kimwonj77/d2coding-nerdfonts/commit/9a41ce6fabd65397280e9c9ad59164ac2831f4ae) and [with `--variable-width-glyphs`](https://github.com/kimwonj77/d2coding-nerdfonts/tree/173307ac3ddbbd20dfb6dcca28466d88bd660167)

Build script is here: https://github.com/kimwonj77/d2coding-nerdfonts/blob/master/build.sh

Also, I'm not a original author of this issue. So I ping you, @Finii. Sorry about this.

**Comment by Finii** [comment] 2023-04-10 10:22
@kimwonj77 Can you show an image were I can see the problem?
If it contains Corean text it would be good to have the text _also_ as text in the comment so that I can try it out.

**Comment by dhnam** [comment] 2023-04-10 12:42
As far as I remember (It has been three years since I found this issue) it was problem of D2Coding font.

As said I exported D2Coding directly from FontForge, but not only that, but I also tried doing same thing with FontLab and python library (as far as remember, as said), and same thing happened.

(I also uploaded same issue at https://github.com/naver/d2codingfont/issues/84 too, which shows attempt to open and re-export the font cause total breakdown of what is written in Korean.)

**Comment by kimwonj77** [comment] 2023-04-10 13:44
First, It's same as original author's image. `다람쥐 헌 쳇바퀴에 타고파`.

![ApplicationFrameHost_VKgjpl39zp](https://user-images.githubusercontent.com/95566897/230912503-c2ec3c6e-6792-4841-84c8-efcb2e794095.png)
mono on windows 11 settings.


![ApplicationFrameHost_Jai9iucMXz](https://user-images.githubusercontent.com/95566897/230912969-3d2e3ab2-c451-4a48-98df-19888dd51e6d.png)
double width on windows 11 settings. but...


![Notepad_mb12W9fgo8](https://user-images.githubusercontent.com/95566897/230912689-238692d4-129c-413c-b141-20e15e38ba39.png)
it's still broken on notepad.

**Comment by Finii** [comment] 2023-04-11 09:55
다람쥐 헌 쳇바퀴에 타고파 = `b2e4` `b78c` `c950` `20` `d5cc` `20` `ccc7` `bc14` `d034` `c5d0` `20` `d0c0` `ace0` `d30c`

Choose for research
* `D2Coding/D2Coding-Ver1.3.2-20180524.ttf` from https://github.com/naver/d2codingfont/releases/tag/VER1.3.2
* https://github.com/kimwonj77/d2coding-nerdfonts/blob/173307ac3ddbbd20dfb6dcca28466d88bd660167/D2Coding/D2Coding%20Nerd%20Font%20Complete.ttf


![image](https://user-images.githubusercontent.com/16012374/231121564-53c01737-71db-4751-b6c0-bc4922cfe527.png)

Looks ok, width is maintained.

Hmm, testing in `tilix`

![image](https://user-images.githubusercontent.com/16012374/231124732-03cb1f52-960f-4784-8c31-3c2aaeb68b84.png)

Looks ok. Maybe it is a Windows problem. _(Comment will be continued on Windows box)_

**Comment by Finii** [comment] 2023-04-11 10:14
Looks ok in windows (so far)

![grafik](https://user-images.githubusercontent.com/16012374/231128026-4633ce84-2912-4a0d-af26-e03f027db2ae.png)

`Windows Terminal`

![grafik](https://user-images.githubusercontent.com/16012374/231129168-f1dd922f-1403-4b58-b9c0-a57990adc8bd.png)

![grafik](https://user-images.githubusercontent.com/16012374/231129282-a6a1bd7e-1d44-4dff-8834-a1de6354aa29.png)

Looks good.

Ah, you use notepad, lets see

![grafik](https://user-images.githubusercontent.com/16012374/231129826-58f86fef-9a2b-45b5-bd5f-febfca0ec63e.png)

Ah!

![grafik](https://user-images.githubusercontent.com/16012374/231130437-f3d1df07-9684-4a24-afd0-d70b72569867.png)

Looks good in writer...

So this is a `wordpad` problem?

**Comment by Finii** [comment] 2023-04-11 10:22
Original font looks good in `notepad`

![grafik](https://user-images.githubusercontent.com/16012374/231132152-59cb6ec0-1403-490a-bee2-e361f6d9fd03.png)

**Comment by kimwonj77** [comment] 2023-04-12 01:21
It's bit difficult to explain, But seem like the rendering method of notepad, and some other programs are using old-school character render system. and it causes the issue. (And also, it only happens on korean character. not english.)

It's also same on `fontview.exe` with korean locale (`fontview.exe`' is locked by windows locale.). Like og author's image.

Also Eclipse
![image](https://user-images.githubusercontent.com/95566897/231314895-bdbb0e03-e3ee-4bd2-8b0f-7a4349ea0e09.png)

**Comment by Finii** [comment] 2023-04-12 06:44
## I found the problem.

The issue is with the `OS/2` `xAvgCharWidth` data in the font.
(`OS/2` is the name of one data table within a open type font (for example `.ttf`))

* For `OS/2` version 0 to 2 the number is the average width of the lowercase latin letters (weighted) [[1]](https://learn.microsoft.com/en-us/typography/opentype/spec/os2#xavgcharwidth)[[2]](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6OS2.html)
* For `OS/2` version 3+ it is the average width of all glyphs

Unfortunately there are multiple bugs here in parallel so I do not really know how to proceed here.

* `notepad` determines the advance width from `xAvgCharWidth` and uses double that value for Korean glyphs (2 cell width) regardless of `OS/2` version :disappointed: 
* The `D2Coding` font says it has an `OS/2` version 3 (!) table but fills the number as version 2 would (probably to circumvent the `notepad` bug :roll_eyes: 
* `fontforge` always fills the version 3 number, even if instructed to create the font with a version 2 `OS/2` table :angry: 

### Possible actions
* Fix `fontforge`'s OS/2 table version 0-2 (will not help because font says it uses version 3)
* Add option to `font-patcher` to create version 2 `xAvgCharWidth` table entry
* Add special rule in `font-patcher` to specific font name to create for this font only a version 2 `xAvgCharWidth`

I do not really like to add options to `font-patcher` if it can be avoided.

**Are there other - possibly Korean - fonts affected of is that only D2Coding?**

[1] https://learn.microsoft.com/en-us/typography/opentype/spec/os2#xavgcharwidth
[2] https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6OS2.html

---

### Fix snippet

```diff
diff --git a/font-patcher b/font-patcher
index 01e144e4c..a82e6f8c5 100755
--- a/font-patcher
+++ b/font-patcher
@@ -135,6 +135,7 @@ class TableHEADWriter:
             positions = {'checksumAdjustment': 2+2+4,
                          'flags': 2+2+4+4+4,
                          'lowestRecPPEM': 2+2+4+4+4+2+2+8+8+2+2+2+2+2,
+                         'avgWidth': 2,
                 }
             where = self.tab_offset + positions[where]
         self.f.seek(where)
@@ -421,6 +422,10 @@ class font_patcher:
                 for idx in range(source_font.num_fonts):
                     if not self.args.quiet:
                         print("{}: Tweaking {}/{}".format(projectName, idx + 1, source_font.num_fonts))
+                    source_font.find_table([b'OS/2'], idx)
+                    dest_font.find_table([b'OS/2'], idx)
+                    dest_font.putshort(source_font.getshort('avgWidth'), 'avgWidth')
+                    dest_font.reset_table_checksum()
                     source_font.find_head_table(idx)
                     dest_font.find_head_table(idx)
                     if source_font.flags & 0x08 == 0 and dest_font.flags & 0x08 != 0:
```

This does not calculate the version 2 number but just copies over the value from the source font. Which would be ok if we just want to fix D2Coding I guess. The code is minimal, just what I used to prove that this is the issue's cause.

**Comment by Finii** [comment] 2023-04-12 06:49
`fontforge` back-links
* https://github.com/fontforge/fontforge/issues/4899
* https://github.com/fontforge/fontforge/issues/1410#issuecomment-164286513

**Comment by Finii** [comment] 2023-04-12 08:25
Even `Glyphs3` does not allow to produce `notepad` compatible fonts...

https://forum.glyphsapp.com/t/font-custom-parameters/1174

**Comment by kimwonj77** [comment] 2023-04-12 11:30
Maybe the Nunum-font series has this problem too. (D2Coding is one of them). But I'm not tested.
https://hangeul.naver.com/font/nanum - All "Nanum" series fonts (for basic usage.) (in Korean)
https://github.com/naver/nanumfont - "Nanum Gothic Coding", an old version of D2 coding.

**Closed** 2023-04-12 14:29 UTC
Labels: confirmed

**Comment by kimwonj77** [comment] 2023-04-12 14:52
Thank you for response! Now I can be happy with Korean font! D2Coding is (if I remember correctly) one and only Korean-Code font since the release...

Also, thank you for reviewing my script! I added it for test just in case.

**Comment by dhnam** [comment] 2023-04-13 12:50
Never expected this issue to be corrected! I just gave up using D2Coding patched with nerd font. But looks like I also can be happy with Korean font!

Huge thanks to both of you, Finni and Kimwonj77!
