### ISSUE TITLE
CaskaydiaCove: letters with diacritics (e.g. ö, é, ę, etc.) look wrong

### ISSUE THREAD

**Issue by yogan** [ryanoasis/nerd-fonts#451] opened 2020-03-13 18:28 UTC
#### 🎯 Subject of the issue

I am currently trying out the patched Cascadia Code font, CaskaydiaCove. It looks really nice, and the extended glyphs are working just fine. However, letters with diacritics, like ö, é, ę, etc., are somehow rendered wrong. They are thinner, and generally have a different shape; it almost looks like they are coming from a different font. The screenshot below shows this pretty well.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
  - `CaskaydiaCove Nerd Font Mono` (also tried `CaskaydiaCove NF`, no difference)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
  - [Windows Terminal](https://github.com/microsoft/terminal), v0.9.433.0
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
  - Windows 10, v1909 (18363.719)

#### ★ Optional

![image](https://user-images.githubusercontent.com/122564/76648909-ecf50300-655f-11ea-861c-1252d75ffd0e.png)

**Comment by craftbyte** [comment] 2020-08-16 12:24
I can confirm this issue, also by checking the original font, the characters are there.

**Comment by wonrax** [comment] 2021-12-15 10:01
It does not support Vietnamese characters too. The original font does.

**Comment by Finii** [comment] 2021-12-15 15:56
It is a font naming problem and would be fixed with #717.

Look here:
![image](https://user-images.githubusercontent.com/16012374/146219307-0790b64f-185f-4518-9287-75322cd8b540.png)

The columns are: Font-Filename, Fullname, Family, Subfamily

It gets the SubFamily wrong, and then the wrong font is choosen because it is grouped (incorrectly) with _Cascadia Code_ that you for shure have installed in parallel.

Solutiion:
* Remove Cascadia Code (is a pain)
* Wait till we correct the naming scheme
* (Hate to say this again, but there is still Delugia, which was just automagically updated to Cascadia v2111.01)

**Comment by Finii** [comment] 2021-12-15 16:08
Here in look into the patched font file in the repo (`patched_fonts/`):
![image](https://user-images.githubusercontent.com/16012374/146221734-24fe42a0-c13f-48ef-939e-f8d9e5c3b4ac.png)

Same thickness. The problem is the font grouping in Windows, which is done (correctly) by Family and not Fullname (and we get that wrong).

**Comment by wonrax** [comment] 2021-12-15 16:14
> It gets the SubFamily wrong, and then the wrong font is choosen because it is grouped (incorrectly) with _Cascadia Code_ that you for shure have installed in parallel.
I actually use CascadiaCode Nerd Font instead of CaskaydiaCove, does this still apply?
![image](https://user-images.githubusercontent.com/28887874/146222210-d20c8a26-5a92-40e0-9113-871cefec506b.png)

And I still don't quite get it, even if it chooses the wrong font, then the characters shouldn't be missing since all the Cascadia fonts I've installed above support Vietnamese characters.

**Comment by wonrax** [comment] 2021-12-15 16:46
I just checked, apparently, my CascadiaCode Nerd Font that I downloaded a while ago is not the same as this font (CaskaydiaCove). I saw the name and wrongfully thought it came from this repository. I just installed the CaskaydiaCove from the `patched-fonts` folder and it supports all the Vietnamese characters. Sorry for the trouble.

**Comment by Finii** [comment] 2021-12-15 17:38
Thanks for the feedback. :)

**Closed by Finii** 2021-12-15 17:38 UTC

**Comment by Finii** [comment] 2021-12-15 17:40
![image](https://user-images.githubusercontent.com/16012374/146237105-e48defa3-5053-41b8-a1d0-9276bf9453db.png)

:sob: 

The naming is broken in so many places.
