### ISSUE TITLE
Victor Mono in Windows Terminal: some characters are very small

### ISSUE THREAD

**Issue by yogan** [ryanoasis/nerd-fonts#1080] opened 2023-01-26 16:51 UTC
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

I have downloaded the Victor Mono zip file the [v2.3.3 release](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3) and tried to use it in Windows Terminal, which _almost_ works, but a few characters are rendered very small.

Experienced behavior:
Some letters are rendered way smaller than the rest for most font sizes. See screenshots below. I've noticed "fi" (ligature) and "g" (regular) in the italic "config" (for the non-italic, it's just the "g"). It also happens for "y". Some font-sizes are fine, e.g. 12 points and 16 points, but those are either too small or too large for my setup to be useable. The regular Victor Mono renders everything fine for e.g. 14 points (which is what I would like to use mostly).

Expected behavior:
All characters should be rendered in the correct font size.

Example symbols:
- "fi", "g", "y"

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Victor Mono * Nerd Font Complete Windows Compatible
   - Victor Mono * Nerd Font Complete Mono
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - [v2.3.3 release zip file](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Windows Terminal Preview, Version: 1.17.1023
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows 11

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/122564/214893626-071feb45-911d-4566-b6bd-5cd6a3ef5f44.png)

![image](https://user-images.githubusercontent.com/122564/214894716-641177d0-b5a1-42ec-88bb-f83c00ce8e4c.png)

![image](https://user-images.githubusercontent.com/122564/214896161-9ee519cd-e910-4822-8ac2-e5dce0692a06.png)

![image](https://user-images.githubusercontent.com/122564/214896240-9b34663e-a7b1-45f6-8edb-44a975bfd4ee.png)
Regular Victor Mono renders everything just fine, but of course the Nerd Font icons are missing.  
"VictorMono NF" and "VictorMono NFM" seem to be exactly the same, "VictorMono Nerd Font" is even worse, the whole italics are not working for that one.  
I've tried to install both the "Windows Compatible" variants, and the "regular" ones. I had no luck with both. :-(

**Comment by Finii** [comment] 2023-01-26 19:47
I fear the family naming is the problem.

Can you remove as many `VicotorMono` fonts as possible? The less you have the better.
Best would be just the plain old style set-of-4:

* `Victor Mono Regular Nerd Font Complete Windows Compatible.ttf`
* `Victor Mono Italic Nerd Font Complete Windows Compatible.ttf`
* `Victor Mono Bold Nerd Font Complete Windows Compatible.ttf`
* `Victor Mono Bold Italic Nerd Font Complete Windows Compatible.ttf`

If that is the cause we can (easily) fix it.

It's important to test with just these 4 fonts (or the 4 `Nerd Font Mono` variants). For Windows do use the `Windows Compatible` fonts (at least for this test). Maybe reboot after changing (uninstalling and installing) the fonts; in some rare cases Windows does not detect changes in fonts I think.

**Comment by yogan** [comment] 2023-01-27 09:31
Hi Finii, thank you for your instructions, I did some further testing based on that. Using only those four variants makes a lot of sense. Initially I was confused by the large amounts of fonts from the zip file and assumed "the more I install, the better" (though I only did with either the "Windows Compatible" set, or the others).

So here is what I have done now:
- completely removed Victor Mono (the original unpatched font w/o NF icons) and all Victor Mono NF variants
- installed just the set of four that you have listed (I'll refer to those as NF4 later on)
- tested font sizes 12-15 in Windows Terminal and took screen shots (NF4)
- installed Victor Mono (the original unpatched font w/o NF icons) again for comparison
- tested font sizes 12-15 in Windows Terminal and took screen shots (original)
- uninstalled NF4, installed the four Mono variants (I'll refer to those as NFM4)
- tested font sizes 12-15 in Windows Terminal and took screen shots (NFM4)

Note that I did not reboot in between, but I did close all instances of Windows Terminal. I think no reboot should be fine, as after uninstall, the fonts were no longer listed (both in Windows Terminal and the Win 11 control center font page). I did have both "Victor Mono" (original) and NFM4 installed - not sure if that could have been an issue, but since my first set of tests with just NF4 (and no original) also showed the issues, I don't think so.

What I have noticed: the effects are worse for some font sizes, and also more present in the italic version.

Something else that I noticed (which is a bit more subtle): in general the letters might be a bit too low, so sometimes the lower parts of letters like "p" and "g" get cut off. That's why I also included screenshots of a status bar with a colored background. When comparing to the original font, you can see that the baseline distance to the bottom is smaller for the patched font. The cutting of can be seen pretty good for "g" in 13 points:
![image](https://user-images.githubusercontent.com/122564/215053281-83d1df2c-7333-4d31-a7e6-d05b1a67a4a4.png)

So here are all of my results, I took three screenshots (regular, italics, and a statusbar with a background) for each of the three font variants (NF4, NFM4, original) in four font sizes.

## Victor Mono {Regular,Italic,Bold,Bold Italic} Nerd Font Complete Windows Compatible
### 12 points
![NF_12_regular](https://user-images.githubusercontent.com/122564/215050994-055bd4e7-3b91-4030-b0b2-b90dd0998037.png)
![NF_12_italic](https://user-images.githubusercontent.com/122564/215051235-54d54899-3496-4651-813f-ffcc4b78d99c.png)
![NF_12_statusline](https://user-images.githubusercontent.com/122564/215051247-2ed2d492-f1e7-4bdf-bc0a-052443a286e6.png)
### 13 points
![NF_13_regular](https://user-images.githubusercontent.com/122564/215051268-dabe8e0d-75c4-495a-b2a4-189b144b7061.png)
![NF_14_italic](https://user-images.githubusercontent.com/122564/215051282-efe177f8-6c4d-44eb-9145-0a7d101deaee.png)
![NF_13_statusline](https://user-images.githubusercontent.com/122564/215051292-cd16497f-a44e-4a7a-8e7c-d9cfd4a4dcae.png)
### 14 points
![NF_14_regular](https://user-images.githubusercontent.com/122564/215051316-9d1e0581-a765-429d-8108-188ee62094da.png)
![NF_14_italic](https://user-images.githubusercontent.com/122564/215051329-edc5dc77-3d69-4d6e-bdae-a83ec2fbbf83.png)
![NF_14_statusline](https://user-images.githubusercontent.com/122564/215051335-c7e03f7d-32ff-41e1-9e5c-3b1910bad324.png)
### 15 points
![NF_15_regular](https://user-images.githubusercontent.com/122564/215051362-b649508d-0257-492a-b3fb-179e7c9ee950.png)
![NF_15_italic](https://user-images.githubusercontent.com/122564/215051385-78eccec6-c33c-4c32-9317-07f0467ce816.png)
![NF_15_statusline](https://user-images.githubusercontent.com/122564/215051399-1f4c8c41-7ab0-4747-acfc-f75e01bdadff.png)

## Victor Mono {Regular,Italic,Bold,Bold Italic} Nerd Font Complete Mono Windows Compatible
### 12 points
![NFM_12_regular](https://user-images.githubusercontent.com/122564/215051674-13f85c74-cdb6-4d73-bee4-fe977445668e.png)
![NFM_12_italic](https://user-images.githubusercontent.com/122564/215051682-142de4e8-bd52-4d65-b53e-4a8819ff5d57.png)
![NFM_12_statusline](https://user-images.githubusercontent.com/122564/215051693-604057e4-7bc5-4ae0-8ad4-f98eea3ebd75.png)
### 13 points
![NFM_13_regular](https://user-images.githubusercontent.com/122564/215051709-d790717f-918d-41b4-8c7b-593ae2994231.png)
![NFM_13_italic](https://user-images.githubusercontent.com/122564/215051723-1b2f821e-f812-4b36-9874-37fd2e7442c0.png)
![NFM_13_statusline](https://user-images.githubusercontent.com/122564/215051738-35cd656a-6245-49db-a23f-ce45f189ae18.png)
### 14 points
![NFM_14_regular](https://user-images.githubusercontent.com/122564/215051763-e1148c67-fc5c-491f-aba0-740fbea091a7.png)
![NFM_14_italic](https://user-images.githubusercontent.com/122564/215051778-0450d70a-9f77-4e39-b7ca-b4a164ae4bc1.png)
![NFM_14_statusline](https://user-images.githubusercontent.com/122564/215051784-2e3029d8-6cd5-493a-991e-6eec09905c38.png)
### 15 points
![NFM_15_regular](https://user-images.githubusercontent.com/122564/215051802-9fe00686-a903-41d1-ad02-e3484146c40b.png)
![NFM_15_italic](https://user-images.githubusercontent.com/122564/215051818-7bc8a6bd-b49a-4390-b1ac-823b336eab98.png)
![NFM_15_statusline](https://user-images.githubusercontent.com/122564/215051833-9825df1c-338b-4e92-9228-a3a01d2caece.png)

## Victor Mono original
### 12 points
![original_12_regular](https://user-images.githubusercontent.com/122564/215051855-4d8a2cdc-6da7-44b4-8bec-d5b033a1109f.png)
![original_12_italic](https://user-images.githubusercontent.com/122564/215051866-327c2b84-e3ef-4205-baac-5a42fa4d4335.png)
![original_12_statusline](https://user-images.githubusercontent.com/122564/215051875-7da74d9f-86fb-47bf-b1fe-8adf2777d7ce.png)
### 13 points
![original_13_regular](https://user-images.githubusercontent.com/122564/215051890-877f1150-8144-4774-bf50-77c772460b17.png)
![original_13_italic](https://user-images.githubusercontent.com/122564/215051911-f16a1c88-a577-4ce8-9467-96c558ecd777.png)
![original_13_statusline](https://user-images.githubusercontent.com/122564/215051935-e578e56f-17f6-44fc-9309-7dc618146dbb.png)
### 14 points
![original_14_regular](https://user-images.githubusercontent.com/122564/215051959-ec93d3ce-ace4-42b5-9143-ded32143fd56.png)
![original_14_italic](https://user-images.githubusercontent.com/122564/215051974-ac6e29e6-b806-476a-9543-421454fcf409.png)
![original_14_statusline](https://user-images.githubusercontent.com/122564/215051988-556f22e7-95bd-44a5-9a00-972131351c2e.png)
### 15 points
![original_15_regular](https://user-images.githubusercontent.com/122564/215052013-ab69907f-10c4-4a5c-ac9c-712d38bbc06d.png)
![original_15_italic](https://user-images.githubusercontent.com/122564/215052022-fa323c0c-046c-4953-955e-6b851e13009b.png)
![original_15_statusline](https://user-images.githubusercontent.com/122564/215052043-9d2eabb1-5ad2-4925-ba2f-5eb72266ddb7.png)

**Comment by A-Lamia** [comment] 2023-03-01 18:31
Having similar issues where new versions (Repeated everything above)
2.3.3:
![image](https://user-images.githubusercontent.com/6450181/222230709-e2b3f156-c49e-47b2-b446-e7bbc5a2ce70.png)
2.3.0-RC:
![image](https://user-images.githubusercontent.com/6450181/222231462-d43627a5-8f30-433c-ad61-d5e2c627d036.png)

honestly I'm not sure what it is but most the fonts are also messed up on on windows in both neovide, windows terminal and wezterm. All the same issue.

**Comment by Finii** [comment] 2023-03-01 19:13
Thanks for reporting @A-Lamia !

Unfortunately in your very constructive critique you do not explain what the concrete issue is.

Maybe you mean the circled glyph
![image](https://user-images.githubusercontent.com/16012374/222240118-c1dc9a0e-528e-45f0-816d-b2a49da90756.png)

that renders 1 cell wide in 2.3.3 and 2 cell wide in 2.3.0-RC. Which can mean that you think 2.3.0-RC is not broken, while 2.3.3 is broken, in that regard. Without any explanation it is hard to offer any help.

Anyhow, if it is about the powerline glyphs, they will be resized with 3.0.0:
* #1123

**Comment by rzabcio** [comment] 2023-04-04 11:28
I have the same problem with Windows Terminal. The biggest problem are "g" that looks like "q" at some sizes, and "_" which... just dissappear.

Everything is ok with original Victor Mono font.

**Comment by Finii** [comment] 2023-04-04 13:55
@rzabcio To make it easier for me to reproduce: Where did you get the font files from, and did you install just one, some, or 'all' (whatever that means)?

**Comment by rzabcio** [comment] 2023-04-05 07:56
I tried two sources, with the same effect.
- https://www.nerdfonts.com/ (downloaded yesterday, .ttf files show 2.3.3)
- community/**ttf-victor-mono-nerd 2.3.3-2** Arch Linux package

(my main OS is Windows, but I work on VM through ssh on Windows Terminal)

I tried Windows Compatible version.

**Comment by Finii** [comment] 2023-04-05 11:32
Did install this set of 4 on Windows 10:

![image](https://user-images.githubusercontent.com/16012374/230062268-dcd37291-2240-4231-bbcf-f10849aefedf.png)

Setting this up in Terminal:

![image](https://user-images.githubusercontent.com/16012374/230062609-4a10a4ea-3b15-4f6d-a958-5248e92c891b.png)

And the result is ok (i.e. can not reproduce):

![image](https://user-images.githubusercontent.com/16012374/230062797-938e9547-b734-4889-aea1-9533f312b5c3.png)

Italic was a bit harder ... ;-)

![image](https://user-images.githubusercontent.com/16012374/230066933-3eb74ae1-0142-45fb-a597-dbabfcf4c773.png)

But what I noticed, that all the letters that seem to be affected in your setup are the ones that are cut off:

![image](https://user-images.githubusercontent.com/16012374/230067376-f7d9bcd9-ea81-409c-aa72-0defe4f455de.png)

This could be an effect of Windows Terminal, because it scales too-big glyphs down.
But why not on my machine?

I have
Windows Terminal
Version: 1.16.10261.0

Anyhow, I guess the cut-off problem is solved with `v3.0.0`, let me check...

**Comment by Finii** [comment] 2023-04-05 12:03
Yes, no more cut off descenders:

![image](https://user-images.githubusercontent.com/16012374/230074267-9f4805ee-e59e-4fa6-958e-435c97192a3e.png)

I think there is quite a good chance that the problem will be fixed by that.

**Comment by Finii** [comment] 2023-04-05 12:09
>     * community/**ttf-victor-mono-nerd 2.3.3-2** Arch Linux package
> 
> (my main OS is Windows, but I work on VM through ssh on Windows Terminal)

Maybe I'm too old :grimacing: but I think I do not understand that. I guess you installed the Arch package in the VM. But the Windows Terminal runs under Windows, so how does the fonts leak out of the VM into the host OS :thinking: 

It's probably not a VM but this ominous Windows Linux Subsystem or how that is called. If you install a font in that Linux subsystem it will end up in the Windows font folder? :grimacing:

**Comment by yogan** [comment] 2023-04-05 14:48
Nope, that is not how WSL works. Installing fonts in a WSL distro should have zero effect on the available fonts in Windows. It should have an effect on graphical Linux apps running via [WSLg](https://github.com/microsoft/wslg#wslg-architecture-overview), but that's not the point here.

**Comment by rzabcio** [comment] 2023-04-05 23:52
You are right, obviously, I just maden a huge shortcut i my description.

I use Arch on VMWare Workstation. I installed there above Arch package, found .ttf fonts in the filesystem, zipped them, scp-d them to host Windows, installed it normally and finally selected it in Windows Terminal. That's the full path, sorry for unclear comment. :⁠-⁠)

**Comment by Finii** [comment] 2023-04-30 15:46
Release is in repo, release as packages pending.

**Closed by Finii** 2023-04-30 15:46 UTC
