### ISSUE TITLE
Release v2.1.0 CascadyaCove Nerd Font Mono contains ligatures

### ISSUE THREAD

**Issue by protiumx** [ryanoasis/nerd-fonts#823] opened 2022-04-22 08:03 UTC
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Mono font contains ligatures

Expected behavior:
Mono font should not contain ligatures

Example symbols:

#### 🔧 Your Setup

- Font: **Caskaydia Cove SemiBold Nerd Font Complete Mono**
- - Download from v2.1.0 artifacts
- Terminal: Kitty
- MacOS, Macbook Pro M1

#### ★ Screenshots (Optional)
<img width="527" alt="image" src="https://user-images.githubusercontent.com/43855513/164644959-7f31f556-2907-4fe4-9ee1-41200d82f7ff.png">

**Comment by Finii** [comment] 2022-04-22 08:13
You ticked _I have searched the issues_ ;-)

Is this not a duplicate of #677?

If you do not need 'SemiBold' but could live with 'Light', 'Regular', and 'Bold', [Delugia Mono](https://github.com/adam7/delugia-code#which-font-faces-are-available) could be a solution for you.

**Comment by Finii** [comment] 2022-04-22 08:26
> I guess the documentation (in its generality) is wrong.
>
> `font-patcher` does not remove ligatures unless [...]

I'm not familiar with `kitty`, but in a lot environments one can turn off ligatures if they are not wanted. Maybe that is possible with `kitty`?

For me (personally) I want the ligatures, and that does not contradict that the fonts are monospaced.

Hmm. I guess the discussion should be continued in #677; please head over there. That conversation went a bit off strict topic, maybe you can get it back on track.

I do not really know what 'people want' and expect from `Nerd Font Mono`. Most people do not understand already the difference between `* Mono Nerd Font` and `* Nerd Font Mono` and what the heck `* Mono Nerd Font Mono` means ;-D

Naming is hard. And doubling (*) the amount of patched fonts in this repo is maybe also a bit harsh.

_(*) Yes, in fact it's only a factor of 1.5_

**Closed by Finii** 2022-04-22 08:26 UTC

**Comment by protiumx** [comment] 2022-04-22 11:52
> You ticked _I have searched the issues_ ;-)
> 
> Is this not a duplicate of #677?
> 
> If you do not need 'SemiBold' but could live with 'Light', 'Regular', and 'Bold', [Delugia Mono](https://github.com/adam7/delugia-code#which-font-faces-are-available) could be a solution for you.

Hi Fini,
I considered it as not duplicated because #677 mentions the `font-patcher` script and this issue is about the fonts contained in the release.
Thank you for the advice.
Kitty does provide config to disable ligatures but it doesn't work, so this ticket can remain closed.

For those who are using Kitty: ligatures seem to be disable by mapping `disable_ligatures_in`
`map alt+1 disable_ligatures_in active always`

Thanks for the help!

**Comment by Finii** [comment] 2022-04-22 12:17
> mentions the font-patcher script [...]
> fonts contained in the release

Ah, yes!

We can not change what is in the 2.1.0 release; the release has been released and will stay like it is forever ;-)
We can just look forward... how will the next release look like? And that is determined by how `font-patcher` will handle the fonts. All the source fonts are patched afresh on release with then then-current scripts.

I'm a bit confused by your anwer about `kitty`. You obviously found the switch to disable ligatures. But that does not solve the problem?

**Comment by Finii** [comment] 2022-04-22 12:22
Ah, and regarding the _MONO shall not contain ligatures_... Please leave your voice in #677. We only know what people want if people voice their needs and concerns etc.

I guess some time in the past (like 10 years ago) Nerd Font _wanted_ to remove _all_ ligatures. But the way invented back ten was tedious and error prone and has been greatly abandoned. But in fact it is very easy to remove all ligatures in the patching process, in a very generic way.
Meanwhile other people might like to keep the ligatures, and are accustomed to have them (because ligature removal has been broken since epochs).
So ... this is just a 'political' decision that needs to be taken.
