### ISSUE TITLE
Patched Iosevka font will remove ligature inside it

### ISSUE THREAD

**Issue by GulajavaMinistudio** [ryanoasis/nerd-fonts#742] opened 2021-12-29 00:38 UTC
There is compatibility issue in Nerd Font Patcher for Iosevka 11 or up version. I try patching Iosevka 11.x with font patcher, but causing ligature removed from it. I want to keep ligature inside Iosevka 11, but the font patcher remove it.

And in Terminal progress, there's some error warning , i think this is causing ligature can't work in Iosevka 11 ?

**"Internal Error: Attempt to output 66740 into a 16-bit field. It will be truncated and the file may not be useful."**

![Screen Shot 2021-12-29 at 07 34 53](https://user-images.githubusercontent.com/11639412/147616965-2595a00d-0ac4-4b06-86b6-6da99b0dd62b.png)

And here is my command to running font patcher
`fontforge -script ./font-patcher ./iosevka-bolditalic.ttf --complete`

Any ide to bring back ligature in patched Iosevka 11's font ?

**Comment by Finii** [comment] 2021-12-30 07:34
Which ligature is it you miss?

**Comment by GulajavaMinistudio** [comment] 2021-12-30 08:45
> Which ligature is it you miss?

After patching with font patcher, **"calt"** and **"dlig"** is removed from Iosevka. I want to keep it like Iosevka v10 and older. But in Iosevka 11, ligation can't be shown because it's removed.

**Comment by xsrvmy** [comment] 2022-01-03 03:31
Running into this same issue (I'm getting a different number though)
https://github.com/fontforge/fontforge/issues/3009
I'm assuming the table responsible for generating ligatures is getting cut off. Iosevka has a LOT of features so maybe that's why.

**Comment by GulajavaMinistudio** [comment] 2022-01-07 15:53
I'm still use font patcher in master branch, and try to use other Iosevka variant called "Iosevka Fixed" that contain no built in ligature and no built in glyph. 
And this run successfully without "truncated error" like previous screenshot with Iosevka and Iosevka Term.

Here is newest screenshot with "Iosevka Fixed" variant
![Screen Shot 2022-01-07 at 22 46 43](https://user-images.githubusercontent.com/11639412/148568860-443809ae-2a55-4775-bf6e-38c1b02e424f.png)

And here package list link for description about Iosevka Fixed. [https://github.com/be5invis/Iosevka/blob/v11.2.4/doc/PACKAGE-LIST.md](https://github.com/be5invis/Iosevka/blob/v11.2.4/doc/PACKAGE-LIST.md)

I think font patcher will get error if there's some built in ligation and glyph, especially in Iosevka or other font like Fira Code.

**Comment by ObserverOfTime** [comment] 2022-02-13 10:34
I have the same issue with Iosevka's `term` spacing but not with `fontconfig-mono`.

**Comment by GulajavaMinistudio** [comment] 2022-03-03 05:01
> Which ligature is it you miss?

Hello Mr Finii, any progress about Iosevka font ? is bug fix is coming with fontforge ? or any workaround ?

**Comment by Finii** [comment] 2022-03-03 05:56
I was able to fix the bug in `fontforge`, and that has been [merged](https://github.com/fontforge/fontforge/pull/4883) (see OberverOfTime's comment above). So if you self-build `fontforge` from HEAD it is fixed. Self-building is not complicated (at least on *ix). When they release a version with the fix, I have no clue.

**Comment by Finii** [comment] 2022-10-29 08:52
In the meantime `fontforge` released a new verion that contains my patch and that error is fix in that fontforge.

So please, use a 2022 March `fontforge` together with the `font-patcher` and all should be well.
This was not a bug in Nerd Fonts.

You can use the `fontforge` AppImage if you have no updated system package, for example:

```
curl -LO https://github.com/fontforge/fontforge/releases/download/20220308/FontForge-2022-03-08-582bd41-x86_64.AppImage
chmod u+x FontForge-2022-03-08-582bd41-x86_64.AppImage
./FontForge-2022-03-08-582bd41-x86_64.AppImage -script .../path/to/font-patcher ...
```

**Closed by Finii** 2022-10-29 08:52 UTC

**Comment by Bahnschrift** [comment] 2022-11-20 06:19
I'm still having this issue with the latest fontforge appimage (20220308).

**Comment by Finii** [comment] 2022-11-20 11:22
> I'm still having this issue with the latest fontforge appimage (20220308).

Well, your problem (#997 after closing) is different than this one here. Previous `fontforge` releases could not write the ligature table at all (i.e. the offsets within the font file were wrong). So the ligature table was destroyed - and `fontforge` detected it, issued a warning.
