### ISSUE TITLE
AnonymousPro: Still blurred fonts

### ISSUE THREAD

**Issue by im-n1** [ryanoasis/nerd-fonts#1174] opened 2023-04-20 16:24 UTC
Back then I reported [this](https://github.com/ryanoasis/nerd-fonts/issues/329) issue. Today I tried new fonts (2 months old) and there is a certain advance but the result is not perfect. See:

Original Anonymous Pro
![not_nerd](https://user-images.githubusercontent.com/198654/233428151-9e0e69c1-e02d-4d8e-bb71-25fd7ef31310.png)

Patched version
![nerd](https://user-images.githubusercontent.com/198654/233428144-cbea493a-cea4-4b6b-b4cb-7de681e3daef.png)

Sizing and spacing seems good but the font is lil bit blurred out and faded.
Terminal: Alacritty  0.12

**Comment by Finii** [comment] 2023-04-20 16:44
The patched from originates where? Release package, self patched, ...?

**Comment by Finii** [comment] 2023-04-20 18:35
Maybe the font is too old. Multiple bugs tackling baseline-to-baseline spacing and also regarding hinting/antialiasing have been fixed for `v3.0.0` which is about to be release. Maybe I should provide you with a new version that you can test. Then I do not need to replicate your issue with an old font and test if it has been fixed with `v3.0.0`. For that I would need to install your client, etc pp (time maybe better spent with preparing the pending release).

**Comment by Finii** [comment] 2023-04-21 04:46
Is 'Original Anonymous Pro' our source or the real source? Because I just noticed we patch a patched version :roll_eyes:

**Comment by Finii** [comment] 2023-04-21 05:03
Obviously the font we use as source is a `Anonymous Pro Minus` variant.

Interestingly the Minus variant (without embedded bitmaps) is available as 1.003 while the ttf with bitmaps in only availabe as 1.002.

I would update our source to the original source. The question remains if you used a self patched font (from the original source), or a pre-patched font? I see that a lot of settings are lost in our source (all the stuff that `fontforge` does not preserver and that we now post-patch copy over from the source font in the 'tweak' stage.

I guess I have a build-from-source `alacritty` somewhere... searching

**Comment by Finii** [comment] 2023-04-21 06:50
Hmm, can not reproduce

![image](https://user-images.githubusercontent.com/16012374/233561649-e5a5ae6b-0af9-4f8a-928e-55a0f3bc9f66.png)
_Top: Original Anonymous Pro; bottom: Anonymice Pro Nerd Font v2.3.3_

Your images looks like one font is rendered with antialiasing and the other without. Maybe.

**Comment by im-n1** [comment] 2023-04-21 07:32
@Finii
1. i use patched font from this repo - master branch
2.  try smalles sizes maybe?
3. my original (the sharp and non patched version) is [this](https://ufile.io/f/x1q2r) one - you can try to patch it by yourself and we will see

**Comment by Finii** [comment] 2023-04-21 08:13
Regarding 3... I just tried to exchange the Anonymous Pro to the real repo (https://www.marksimonson.com/fonts/view/anonymous-pro), but that font triggers a bug in fontforge :-( https://github.com/fontforge/fontforge/issues/5230

So now I started to debug `fontforge` ...
Maybe I should stop that soon, and continue on with 3.0.0 :thinking:

**Comment by Finii** [comment] 2023-04-21 11:18
The embedded bitmaps almost certainly are destroyed by fontforge...:

![image](https://user-images.githubusercontent.com/16012374/233623184-13bb81bd-ce80-46bf-b173-3f64f56f2259.png)

Looks good otherwise.

**Comment by im-n1** [comment] 2023-04-21 12:55
So the issue is in fonrforge which means you cant do anything about that?

**Comment by Finii** [comment] 2023-04-21 14:11
No, at least I do not believe that. When I use the original Anonymous Pro `alacritty` says something contradicting regarding bitmaps...:

![image](https://user-images.githubusercontent.com/16012374/233653421-103db235-56fd-448e-ac01-d98f37d48202.png)

I'm not sure what that means. Anyhow, the bitmaps are only in sizes 10..13, and I guess you see the problem also with bigger sizes? Your screenshot looks like bigger size.

I have very limited knowledge about bitmap fonts, while according to #329 you have :-)
So from the looks it seems that the bitmaps are broken (if the bitmaps are used in your setup).
I have no clue how it should look like in `alacritty -vvv` when bitmaps are used, and/or how I enforce bitmaps, etc pp.
I have a problem with `alacritty` anyhow, the usual executables do not run on my machine - that is the reason why I self-built that thing. Maybe it's my unsupported graphics :woman_shrugging: 

Before commit 946c1d09ddf0a3d5f71f0ce3edb3da2bf2fceedb `font-patcher` was not even able to preserve bitmaps at all.
That is in `v2.3.0-RC`, so it should be in the fonts you downloaded. Ah no, the **source** did not contain bitmaps.

I can prepare you a new `AnonymicePro Nerd Font v3.0.0` that you could check. Because that will really include bitmaps, maybe that will be the difference then. Or do you see the effect also with bigger sizes, beyond bitmaps?

As I showed, I can not see the effect right now.
I believe you are on Arch, maybe I remember wrongly. What you could try is changing the antialiasing and hinting settings - although I do not know if `alacritty` even obeys them. Maybe that will point us in the right direction.

And/or it would be helpful to check if the effect is also there in other applications. Other terminals and also text processors like `writer`.

![image](https://user-images.githubusercontent.com/16012374/233657247-62e41b35-c9dc-426b-8f23-31b15fdfbde8.png)
_Antialias and Hinting settings for Gnome_

**Comment by Finii** [comment] 2023-04-21 14:33
Please find the patched-with-bitmaps fonts here: https://github.com/Finii/nerd-fonts/tree/master/patched-fonts/AnonymousPro

**Comment by Finii** [comment] 2023-04-21 14:45
Some tables are missing after patching, and `EBDT` (Embedded Bitmap Data Table) is smaller :roll_eyes: 

![image](https://user-images.githubusercontent.com/16012374/233665445-b6e8c5c0-880c-4494-a7ee-08d35d0bf301.png)

**Comment by Finii** [comment] 2023-04-21 14:59
Had a look at your screenshot in huge magnification...
This for sure looks like hinting hitting you...

![image](https://user-images.githubusercontent.com/16012374/233668107-b55516a8-105f-456f-84a5-072c96dc0ba5.png)
_Bottom-right: Original font. Click to enlarge_

Patching did not show a baseline-to-baseline metrics warning, so that is probably also solved meanwhile.

**Comment by Finii** [comment] 2023-06-04 16:10
Already did the change to bitmap embedded Anonymous Pro with #1175.

Please check after `v3.0.2` if that has been improved.

Closing for now.

**Closed by Finii** 2023-06-04 16:10 UTC
