### ISSUE TITLE
Mono fonts not selectable in KDE and Konsole

### ISSUE THREAD

**Issue by Scrumplex** [ryanoasis/nerd-fonts#277] opened 2018-06-10 13:11 UTC
#### 🎯 Subject of the issue
I can't select any Mono Nerd Font in Konsole's font settings.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
 Source Code Pro Nerd Font Mono
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
 Konsole 18.04.2
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
 Arch Linux

**Comment by westernmagic** [comment] 2018-06-20 15:31
Duplicate of #269, #270?

**Comment by Scrumplex** [comment] 2018-06-20 15:35
#270 may be a possible duplicate. I don't think #269 is, as it is a completely different OS.

**Comment by haasosaurus** [comment] 2018-07-20 02:25
https://github.com/ryanoasis/nerd-fonts/issues/270 https://github.com/ryanoasis/nerd-fonts/issues/269 https://github.com/ryanoasis/nerd-fonts/issues/268 are all duplicates. see pr https://github.com/ryanoasis/nerd-fonts/pull/283
you can try the patched fonts in this branch of my fork temporarily until the next version is released if you want https://github.com/haasosaurus/nerd-fonts/tree/regen-mono-font-fix

**Comment by Finii** [comment] 2023-01-28 15:48
Should be fixed since `v2.2.2` via
* #764

**Closed by Finii** 2023-01-28 15:48 UTC
