### ISSUE TITLE
Unable to change default glyphs

### ISSUE THREAD

**Issue by RiccardoMPesce** [ryanoasis/nerd-fonts#158] opened 2017-04-25 12:02 UTC
I'am using powerlevel9k, with Droid Sans Mono nerd font, on AntergOS (Arch Linux), on Gnome-Terminal (Gnome version 3.24).
I cannot change the glyphs of some icons, indeed if I try something like this `POWERLEVEL9K_VCS_GIT_GITHUB_ICON="\uE709" ` nothing actually changes. Any way to fix it?

**Comment by ryanoasis** [comment] 2017-04-25 22:30
@RiccardoMPesce Thanks for the report but I don't think the issue is with Nerd Fonts.

![selection_041](https://cloud.githubusercontent.com/assets/8083459/25410526/4c4fad82-29e5-11e7-9de6-c99804ba1916.png)

**Comment by agriffis** [comment] 2017-04-26 12:55
@RiccardoMPesce Your shell syntax is incorrect. Use this:

```shell
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=$'\uE709'
```

See https://www.gnu.org/software/bash/manual/bash.html#ANSI_002dC-Quoting

**Comment by ryanoasis** [comment] 2017-04-26 23:41
@RiccardoMPesce Seems like this is not an issue. I am going to close this for now.

Thank you both.

**Closed by ryanoasis** 2017-04-26 23:41 UTC
