### ISSUE TITLE
Icon nf-oct-file_directory changed on update to 3.0.0

### ISSUE THREAD

**Issue by Mangeshrex** [ryanoasis/nerd-fonts#1207] opened 2023-05-06 06:13 UTC
Hey, I actually love an icon from the version 2.3  nerdfonts as due to the commit of modernizing the fonts, that glyh was uncertainly removed from it. One of my friend managed to get the file for that file from some other repo. 

So, I copied that font to a different file and managed to make a generate a new font with only that icon in the file with the help of fontforge. But the issue is when i'm using a font from the v3.0 the icon is hollow and If I use the older version it is how I expect it to be. 

Expectations (tested on font from v2.3) for v3.0
![Sat May  6 11:39:49 IST 2023](https://user-images.githubusercontent.com/82205152/236604623-31c284e0-3e94-40fb-9f4b-0f00b98de371.png)

This is how it is when using v3.0 fonts 
![Sat May  6 11:11:36 IST 2023](https://user-images.githubusercontent.com/82205152/236604777-bd07db33-525d-4be8-895f-20769954f186.png)

- [x ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [ x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [ x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

This is the symbol / glyph I want to be like expected above
 

## My Setup 
Arch Linux

**Comment by Finii** [comment] 2023-05-07 07:29
Is this about the directory/folder icon?

**Comment by Mangeshrex** [comment] 2023-05-07 11:28
yes

**Comment by Mangeshrex** [comment] 2023-05-07 11:31
could you please provide some help ? as it's very urgent

**Comment by Mangeshrex** [comment] 2023-05-07 12:14
also there's an endpoint in nerd fonts with the same endpoint as the one which I created in the separate file. So maybe the nerd font one is overlapping the one I made. So, is it that I have to create a new endpoint and shift this icon to that endpoint ?

**Comment by Finii** [comment] 2023-05-07 12:34
This in a duplicate of the comment here: https://github.com/ryanoasis/nerd-fonts/issues/1190#issuecomment-1532632029

You seem to be missing the same glyph?

![image](https://user-images.githubusercontent.com/59060246/235865321-750637d5-54b7-471e-b3b2-b0659556a713.png)

Octicons updated their design and a lot of their icons got modernized and unified in that process.

If it's just that it is 'open', maybe try one of their others:

![image](https://user-images.githubusercontent.com/16012374/236677791-a08ade6f-ba8a-4a6f-99a1-c2ed507d3e4b.png)

Or enter `folder` on the [cheat sheet](https://www.nerdfonts.com/cheat-sheet) and see if there is anything you can stand...


If you want to self patch and have a one-glyph font with the old icon and THAT does not render correctly, I could possibly help if I can get the hands on your font and font-patcher log.

**Comment by Mangeshrex** [comment] 2023-05-07 12:39
`could you please guide me on self patching ? I actually want the same glyph which is now turned into an unfilled or hollow icon. It'

**Comment by Finii** [comment] 2023-05-07 13:39
If you start with a already patched font and just want to patch that one glyph over from the single-glyph font.

The glyph you want to patch needs to be on the correct codepoint already (no movement possible).

Then do `fontforge font-patcher --custom my_single_glyph_font.ttf --glyphdir path/to/the/font/file`

I'm not sure what will happen to the font name, probably it will be broken :-|
It also depends on which font you started with, different fonts need different renaming setting.
Hmm, there is no 'no not change the naming' option.

So in principle what you would need to do is:

* Start with the unpatched font(s)
* Find out which `makegroups` mode it needs (`src/unpatched-fonts/**/config.cfg`)
* Copy the single-glyph font into `/src/glyphs/`
* Patch the fonts with `-c --custom my_single_glyph_font.ttf --makegroups 4` (4 -> whatever is needed 1-6)
* Of course add `--mono` or `--propo` on whatever the aim is

Or use the `patch-em-all` script, if you have it:

* Copy the single-glyph font into `/src/glyphs/`
* Patch the fonts with
  `NERDFONTS='--custom my_single_glyph_font.ttf' ./gotta-patch-em-all-font-patcher\!.sh -cj /FiraMono`
* (FiraMono is the `src/unpatched-fonts/` subdir name, adapt accordingly)
* The `NERDFONTS` environment variable is used to transport more options through the patch-em-all
* The `makegroups` will be automatically correct now

(Nothing tested, just from the top of my head)

**Comment by Finii** [comment] 2023-05-07 13:40
The `-c` option to `gotta-patch-em` puts the resulting font in `check-fonts/` instead of `patched-fonts/`. Of course you do not need to give it, it just helps not messing up your repo ;-)

**Comment by Mangeshrex** [comment] 2023-05-07 17:33
Thanks for all the help you''ve provided. I'll try this tomorrow morning as it's very late as of now. Also, please don't close this issue now itself ;)

**Comment by Finii** [comment] 2023-05-09 16:50
@siduck expressed the plan to re-package the modified fonts and have thus a different set up `Nerd Fonts` that are not Nerd Fonts. They should then create a fork and **change the name**, or whatever. But that plan will result in confusion.

Please do not do this.

**Closed by Finii** 2023-05-09 16:50 UTC
