### ISSUE TITLE
Terminal missing fsharp icon

### ISSUE THREAD

**Issue by Nojpg** [ryanoasis/nerd-fonts#672] opened 2021-09-28 15:02 UTC
#### 🎯 Subject of the issue

Fsharp files are without icons in terminal. But vim can see icons from nerd font. In the screenshots you can see what i mean. 

#### 🔧 My Setup

- Font: JetBrains Mono Medium Nerd Font Mono
- Terminal: checked on gnome and alacritty
- OS: Linux

#### ★ Optional

![image](https://user-images.githubusercontent.com/15429565/135111948-6f2b50f2-53a9-4966-a4a3-98ce0573eafe.png)
![image](https://user-images.githubusercontent.com/15429565/135112016-11876b13-2b30-4ceb-8e76-66874002bed3.png)

**Comment by Finii** [comment] 2021-11-22 10:17
The issue is that `ls` does not show the existing `$i_dev_fsharp`?

**Comment by ryanoasis** [comment] 2021-12-12 02:13
your screenshot seems to suggest the problem is not with the font itself as `echo $i_dev_fsharp` works as expected.

Have you modified `ls` to show glyphs or using something like https://github.com/athityakumar/colorls ?

**Comment by Nojpg** [comment] 2021-12-15 18:39
> your screenshot seems to suggest the problem is not with the font itself as `echo $i_dev_fsharp` works as expected.
> 
> Have you modified `ls` to show glyphs or using something like https://github.com/athityakumar/colorls ?

yes, other icons(json etc..) are work well

**Comment by Nojpg** [comment] 2021-12-15 18:39
> The issue is that `ls` does not show the existing `$i_dev_fsharp`?

yes

**Comment by Finii** [comment] 2021-12-16 05:44
It should show `uE7A7` according to https://github.com/ogham/exa/blame/master/src/output/icons.rs

![image](https://user-images.githubusercontent.com/16012374/146314536-ddf850da-8996-4ecb-a09f-66777589cf2b.png)

Are you sure your `exa` is new enough to have fsharp?

It is in the font...:
![image](https://user-images.githubusercontent.com/16012374/146314917-ea7aa805-7574-4192-8ed7-42af707c3da2.png)

I believe you need to update your `exa`. Did you try HEAD or something?

Will close this, please reopen if you have a fsharp-enabled exa, and it still does not work.

**Closed by Finii** 2021-12-16 05:44 UTC

**Comment by Finii** [comment] 2021-12-16 06:52
In fact you need to build it yourself, as 0.10.1 is the latest release:

![image](https://user-images.githubusercontent.com/16012374/146322235-7bd93a31-7a9f-468c-9db1-f30e04b4db61.png)

Maybe you should try to build HEAD (if you did not already; if you did, please reopen).
