### ISSUE TITLE
Wrong size of the Fira Code glyphs

### ISSUE THREAD

**Issue by mateusz-bajorek** [ryanoasis/nerd-fonts#898] opened 2022-08-29 08:20 UTC
#### 🗹 Requirements
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

##### Experienced behaviour:
After upgrading from 2.1.0 to 2.2.1, the size of the glyphs in Windows Terminal is wrong (smaller) when using FiraCode font.

##### Expected behaviour:
The size of the glyphs is correct.

#### 🔧 Your Setup

- `Fira Code Regular Nerd Font Complete Windows Compatible.ttf`
   - either downloaded from the releases page or installed through `scoop.sh`
- Windows Terminal
- Windows 11

#### ★ Screenshots (Optional)

Size of the glyphs when using release 2.1.0:
![WindowsTerminal_2022-08-28_12-01-37](https://user-images.githubusercontent.com/11185738/187155589-19501048-a1f6-42b9-afd3-db15ede0cd5c.png)

Size of the glyphs when using release 2.2.1:
![WindowsTerminal_2022-08-28_12-01-48](https://user-images.githubusercontent.com/11185738/187155618-9d84d673-1f28-4dcf-ad6f-231d937b9c6b.png)

Windows Terminal settings dialog:
![WindowsTerminal_2022-08-29_10-14-28](https://user-images.githubusercontent.com/11185738/187155887-63e7ef62-bcae-4bda-ab14-7dc64ada67e4.png)

**Comment by Finii** [comment] 2022-08-29 10:55
Can reproduce

![grafik](https://user-images.githubusercontent.com/16012374/187182340-b06a977e-e944-4e88-aa67-1174b3cb7c47.png)


* Installed just the one font file.
* Gitlab glyph `F296`
* Font looks good in fontforge ('gitlab' is 1951 wide, normal letter is 1200)
* `Windows Terminal` says glyph width is `ambiguous` https://github.com/microsoft/terminal/blob/deffbbc7f52a3e41aaf760977a907d326382848b/src/types/CodepointWidthDetector.cpp#L246
* `Windows Terminal` thinks the glyph needs to be small (i.e. 1 cell wide) and scales down accordingly

* This seems to be an instance of (would be fixed by) #764
* On the other hand there are several issues open at `Windows Terminal`
* Note DHowett's comment https://github.com/microsoft/terminal/issues/6738#issuecomment-652077541

**Comment by Finii** [comment] 2022-08-29 11:00
While this is confirmed, it is still open what one would expect.

There are people that want the fonts to be 'correct'.
'Correct' fonts are considered incorrect by `Windows Terminal`

`Windows Terminal` would reject the font anyhow, you need to check 'all fonts' so that you could take it.

This is kind of a political question. So there is no simple answer to it.

I leave this open, but the behaviour is 'as expected', the bad this is.

**Comment by Finii** [comment] 2022-08-29 12:57
Duplicate of #731, still current with `v2.2.1`.

**Comment by saumyajyoti** [comment] 2022-08-31 04:29
> symbols pretend to be same width but 'secretly' protude out of the 'cell'
Is there a way we can generate this now with latest Source? Want to try locally.

**Comment by Finii** [comment] 2022-08-31 05:44
No, unfortunately. I started #900 to re-investigate and come up with a solution.

I just noticed that also `fontforge`'s behavior changed, so patching with the `v2.1.0` script yields other results now then before \*sigh\*. 

But I guess this week.

**Comment by saumyajyoti** [comment] 2022-08-31 11:07
I reverted change 59c45ba4eff539d2a83a7d7004f056b9860d3253 and ran locally. I am able to get IOSEVKA 16.0.2 working as intended.

**Font Settings Win11**
![image](https://user-images.githubusercontent.com/27477973/187664586-c7faa4ae-1d74-4ebb-8233-b1d0183733dc.png)

**Terminal Win11**
![image](https://user-images.githubusercontent.com/27477973/187664734-64fa52c2-119f-404e-849e-d186ecaaa582.png)

**Comment by Finii** [comment] 2022-08-31 12:04
Which `fontforge` version did you use? I noticed that with `HEAD` the behavior changed when removing the bearings.

**Comment by saumyajyoti** [comment] 2022-08-31 12:50
I used Version: 20220308.
Not sure how to confirm the left bearing value.
I use commandline: ffpython font-patcher -c -w -l --careful

**Comment by Finii** [comment] 2022-08-31 13:07
What is `ffpyhon` :grimacing: 

> confirm the left bearing value

Left bearing is zero (all 'overhang' is on the right) (image taken from #764)

![image](https://user-images.githubusercontent.com/16012374/187685050-7b91c4ce-007b-4cc4-bce6-704181ad44dd.png)

What I got yesterday:

![image](https://user-images.githubusercontent.com/16012374/187685461-c1f29d7a-3476-481c-8d47-7524c9881e9d.png)

(different symbol, because I did not do `--complete` but just the basic stuff)

**Comment by saumyajyoti** [comment] 2022-08-31 14:49
Thanks. ffpython is python exe packaged in font-forge release.  As the font patcher is w/o extension, windows does not run python by default, so running with python bundled with font-forge.

**Comment by Finii** [comment] 2022-09-01 05:48
@saumyajyoti You are right! Thanks! I do not know what went wrong when I tested it, but I did a fresh (manual) revert and it works.

Now exploring how to solve the Arch issue that the commit should have addressed in a different way.

**Closed** 2022-09-07 06:00 UTC
Labels: ♒ duplicate, confirmed
