### ISSUE TITLE
CJK characters are misaligned when using Nerd Fonts

### ISSUE THREAD

**Issue by SAPikachu** [ryanoasis/nerd-fonts#161] opened 2017-05-09 02:21 UTC
#### Subject of the issue

CJK characters are misaligned when using Nerd Fonts. Bottom part of the text is cut off.

#### Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
Ubuntu Mono Nerd Font Complete Mono.ttf

- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
konsole (with XMing as X server)

- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Ubuntu 16.04

#### Optional

- _Provide **screenshots** where appropriate_
![nerd-font-cjk](https://cloud.githubusercontent.com/assets/653824/25832974/c627ae5a-34a0-11e7-96a9-3c53d4cde56d.png)

**Comment by ryanoasis** [comment] 2017-05-10 23:14
@SAPikachu Appreciate this report. Thank you :+1: 

Do you know if the issue happens when using the un-patched version of the font: [Anonymice Powerline](https://github.com/ryanoasis/nerd-fonts/blob/master/src/unpatched-fonts/AnonymousPro/Anonymice%20Powerline.ttf) ?

**Comment by SAPikachu** [comment] 2017-05-11 00:40
@ryanoasis I am not sure at this time, but I can test it a bit later (probably this weekend). Stay tuned. :)

**Comment by SAPikachu** [comment] 2017-05-13 05:39
@ryanoasis Anonymice Powerline has the same issue. Just for your information, the system Ubuntu Mono font doesn't have this issue.

![anonymice](https://cloud.githubusercontent.com/assets/653824/26022824/4def7be0-37e1-11e7-9ec2-e6e45f1249f0.png)

**Comment by ryanoasis** [comment] 2017-05-13 13:17
@SAPikachu thanks for the update! :smile: Seems like it is an issue with the original unpatched (but Powerline patched font).

What if you try the true [Anonymous Pro](http://www.marksimonson.com/fonts/view/anonymous-pro) ?

**Comment by SAPikachu** [comment] 2017-05-13 13:28
@ryanoasis It has the same issue:

![original-anonymous-pro](https://cloud.githubusercontent.com/assets/653824/26025849/0fd582e0-3823-11e7-9e23-77f5334afe28.png)

**Comment by ryanoasis** [comment] 2017-05-13 14:00
@SAPikachu Thanks again. This doesn't seem to be an issue with Nerd Fonts. Also those characters seem to not be coming from any of these fonts but rather from `Noto Sans CJK JP`.

I have the same issue with `terminal` compare to `gnome-terminal`. Best case these characters seem too low vertically? Worst case they are cut off at the bottom.

![selection_003](https://cloud.githubusercontent.com/assets/8083459/26026069/aeccce28-37c2-11e7-83b5-8a6c82b0d959.png)

I was able to improve things just a bit with line spacing but like I said they are still appearing too low:

![selection_004](https://cloud.githubusercontent.com/assets/8083459/26026076/e94761a8-37c2-11e7-9942-59b68a2f7ac9.png)

**Comment by be5invis** [comment] 2017-05-13 14:02
Looks like the terminal cannot handle fallback.
Hmmm pretty common.

**Comment by ryanoasis** [comment] 2017-05-13 14:11
@be5invis Thanks for chimming in :smile: 

Looks like `gnome-terminal` does a better job at least in this sense. I haven't played around with many term emulators recently and certainly not with CJK range :blush: 

Here is an interesting possibly related issue: https://unix.stackexchange.com/questions/318909/how-do-i-fix-this-text-rendering-issue-in-konsole

Here is another interesting comparison of some breakdown:

![selection_005](https://cloud.githubusercontent.com/assets/8083459/26026162/8a4cb28c-37c4-11e7-8eaf-29a1b681ac2d.png)

**Comment by SAPikachu** [comment] 2017-05-14 01:12
@ryanoasis Thanks for checking! I didn't realize that it is an issue in Konsole (I recently switched from lxterminal to Konsole, and the test of original Ubuntu Mono was done on lxterminal. I just tested on Konsole and got the same issue), sorry about that! For the record, I just found a relevant bug: https://www.mail-archive.com/kde-bugs-dist@kde.org/msg80564.html

**Comment by msva** [comment] 2017-05-14 06:38
Actually, it is not exactly KDE Bug. The problem is described in pre-last 
comment there.

By the way, it looks like it was already fixed in KDE 17.04: https://
bugs.kde.org/show_bug.cgi?id=371687#c9

I just tested, and... vertical align looks like really fixed: http://
i.imgur.com/JcBUl2c.png

But as you can notice, it is another issue appeared (it does not fit all the 
characters horizonatlly, and the ones that does not fit, somewhy got partially 
rendered on the scrollbar :D

--

> @ryanoasis Thanks for checking! I didn't realize that it is an issue in
> Konsole (I recently switched from lxterminal to Konsole, and the test of
> original Ubuntu Mono was done on lxterminal. I just tested on Konsole and
> got the same issue), sorry about that! For the record, I just found a
> relevant bug:
> https://www.mail-archive.com/kde-bugs-dist@kde.org/msg80564.html

**Comment by ryanoasis** [comment] 2017-05-19 02:03
So this seems like terminal specific issue for sure. I am going to close this for now.

Thanks all :smile:

**Closed by ryanoasis** 2017-05-19 02:03 UTC
