### ISSUE TITLE
Scala filetype icon missing for InconsolataForPowerline Nerd Font Mono.otf

### ISSUE THREAD

**Issue by jinmel** [ryanoasis/nerd-fonts#92] opened 2016-06-18 06:27 UTC
#### Subject of the issue

Scala filetype icon not rendering properly when using Inconsolata for powerline Nerd Font _Mono_
#### Your Setup

terminal in use : urxvt 256 color
font name: Inconsolata for Powerline Nerd Font Mono.otf from `minimal` folder
Xresources font settings:
URxvt.font: xft:InconsolataForPowerline Nerd Font:pixelsize=16:antialias=false:hinting=true

Screenshot:

![screenshot from 2016-06-17 23 24 01](https://cloud.githubusercontent.com/assets/2859853/16169433/c5303a12-34e2-11e6-8f31-db15d931470a.png)

Possible cause of error:

Other file type glyphs render properly except the scala glyph. The urxvt doesn't know how to render variable width font so it is likely that scala glyph in included in the font isn't mono

**Comment by ryanoasis** [comment] 2016-06-18 15:57
Yikes, yeah I can see a problem with even other glyphs as well.

![selection_18_06_16_11 54 35_196x384_001](https://cloud.githubusercontent.com/assets/8083459/16171984/c47a3852-354b-11e6-9626-90716e682da5.png)


Honestly it's been a long time since I've looked at what is happening with the single width glyphs, they don't all seem to get adjusted properly.

**Comment by blueyed** [comment] 2016-10-20 03:06
FWIW: urxvt tends to throw away too wide glyphs.

**Comment by zeorin** [comment] 2016-10-20 09:00
@jinmel Are you using the `URxvt.letterSpace` setting at all? I found that to have an impact on how many glyphs were not rendered by urxvt. I have to set it to `-2` for spacing on Knack to look right.

It's worth mentioning @blueyed's fork https://github.com/blueyed/rxvt-unicode/tree/display-wide-glyphs. I use it myself and it works quite well: I don't even use the Mono versions of nerd fonts.

The way I understand it, instead of using a glyph's *spacing* to determine it's rendering, urxvt uses each glyph's *width* to render it. If a glyph is very slightly too big it'll try to render it, but if it's too big it'll just show the rectangle instead. The forked version fixes it to use spacing instead of width. The maintainer of the original repo [won't merge the patch](http://lists.schmorp.de/pipermail/rxvt-unicode/2014q4/002042.html).

I had to build a new package on Debian, which is a mission if you're familiar with the process of doing it The Debian Way™. I had to get a patch, which I did by cloning the original urxvt git repo, adding the fork as a remote, fetching it, and then getting the patch like this: `git diff origin/master...blueyed/display-wide-glyphs > display-wide-glyphs.patch`.

See [this Superuser answer](http://superuser.com/a/1074285) by @blueyed for more information and a link to an Arch AUR for a pre-patched version.

**Comment by blueyed** [comment] 2016-10-20 11:09
@zeorin 
Thanks! :)
It is currently not included in Arch's rxvt-unicode-patched however, because it caused crashes that I could not reproduce. I am glad it works for you! :)
I have looked into some minor issues with my branch during the last days and learnt a lot about urxvt's internals on the way.

I am experimenting with a hack that uses the font itself to get the width (instead of using the wcwidth system function, which is meant to return what the Unicode spec thinks).
Since a lot of (all?) of the glyphs in this font are from the private space, where the width is defined as ambitious, this should work better and is probably the way to go with codepoints from the private space?!
It will use this method inside of rxvt-unicode itself, and the injects wcwidth through LD_PRELOAD to the terminal's child process, communicating through pipes then..

(btw: with Unicode 9 emojis have a width of 2 now finally, but glibc is not yet updated for Unicode 9, and it does not affect the glyphs from this font)
See https://github.com/termux/wcwidth/issues/1, and the project itself for a C version that is Unicode 9 compatible.

Unfortunately both Vim and Neovim do not use the system's wcwidth function, but their own version, so you cannot inject a new one using LD_PRELOAD directly.
I think I should push my branch and not hijack this issue further.. ;)

The takeaway however is that urxvt is very strict in this regard.

**Comment by ryanoasis** [comment] 2016-11-01 02:37
This is probably still a problem but if anyone wants to attempt to see if the [fonts in 0.9.0 branch](https://github.com/ryanoasis/nerd-fonts/tree/0.9.0/patched-fonts) help solve the issues go for it :smile:

**Comment by ryanoasis** [comment] 2019-10-21 01:04
Closing due to age of issue and that this has workarounds in terms of terminal or using one of the mono Nerd Fonts (single width glyphs).

**Closed by ryanoasis** 2019-10-21 01:04 UTC
Labels: ⚠ bug, ❲⌖❳glyph positioning, ❲⚖❳glyph sizing
