### ISSUE TITLE
[Feature request] - display progress bar instead of popup while installing nerd fonts using Powershell script

### ISSUE THREAD

**Issue by NileshGule** [ryanoasis/nerd-fonts#788] opened 2022-02-16 18:49 UTC
#### 🗹 Requirements

I tried installing the nerd font by downloading the repo and running the install.ps1 Powershell script. It has been running for close to 30 minutes. Every font installed is shown in the popup

#### 🎯 Provide installation updates in a progress bar

It is quite irritating to see the popup with font name appear every few seconds on the screen.

#### 🔧 Your Setup

- All fonts
- Windows Terminal
- Windows 11

#### ★ Screenshots (Optional)

![nerdfonsts install](https://user-images.githubusercontent.com/1298374/154334982-50e480ee-477b-4fc2-b832-a8205a4eed47.png)

**Comment by Finii** [comment] 2022-02-17 17:12
I tried this:
![image](https://user-images.githubusercontent.com/16012374/154533057-68918cde-e153-4895-8a5c-9f733e721748.png)

and - as I feared - it tries to install all and any `*.[ot]tf` file.

Would it not make more sense to just install `Windows Compatible` version or so? Or at least only all `non Windows Compatible` OR all `Windows Compatible`? Does it make sense to install every font two times?
No wonder that it takes ages...

**Comment by eo1989** [comment] 2022-03-02 16:45
Read the instructions. They explicitly say not to blindly git clone the entire repo as you will clone every permutation of every font in the repo..

**Comment by Finii** [comment] 2022-03-03 07:16
I see no indication here that `git clone --depth 1 ...` has **not** been used.

The Issue is about the time the install process via `install.ps1` takes, and that there is no 'total' progressbar.

**Comment by Finii** [comment] 2023-05-12 15:49
Thanks for the suggestion, @NileshGule !

Unfortunately I have no clue how one could suppress these popups.
Any hints welcome.

Moving this to 'future'.

**Comment by Finii** [comment] 2023-05-12 15:49
Resides now (closed) in the future milestone.

**Closed by Finii** 2023-05-12 15:49 UTC
Labels: help wanted, ➤ future
