### ISSUE TITLE
Remove the empty glyph from 1000-em variants at codepoint U+0045 (Latin capital letter `E`)

### ISSUE THREAD

**Issue by arnavyc** [ryanoasis/nerd-fonts#765] opened 2022-01-17 06:02 UTC
#### 🗹 Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki) for help

#### 🎯 Subject of the issue

All 1000-em variants contain an empty glyph at codepoint U+0045 (Latin capital letter E)

#### 🔧 Your Setup

- _Which font are you using?_ - Fira Code with fontconfig (Arch package [`ttf-nerd-fonts-symbols-mono`](https://archlinux.org/packages/community/any/ttf-nerd-fonts-symbols-mono/))
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ GNOME terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Arch Linux

#### ★ Screenshots (Optional)

Looking at TTF in fontforge (https://github.com/ryanoasis/nerd-fonts/issues/581#issuecomment-837335900)

![image](https://user-images.githubusercontent.com/13703064/149715648-40e3137f-119c-4e4c-8b4b-ead93ca796fa.png)

#### Suggestion

Remove the empty glyph from 1000-em variants at codepoint U+0045 (Latin capital letter `E`). This will also fix #581.

**Comment by Finii** [comment] 2022-01-17 10:10
See #753, marked there as 'fixed' but maybe only the main issue not the `'E'`

> Additionally:
All 1000-em variants contain an empty glyph at codepoint U+0045 (Latin capital letter E) !??

**Comment by WhyNotHugo** [comment] 2022-03-03 11:23
Duplicate of #581?

**Comment by Finii** [comment] 2022-03-03 11:36
Thank you for the input.

TO references that Issue already in the description.

But didn't Ryan already address that? It's still open :thinking:

**Comment by Finii** [comment] 2022-03-03 12:02
It IS solved, see https://github.com/ryanoasis/nerd-fonts/issues/581#issuecomment-1057969427

Doublechecking...
:-o

What the heck?

**Comment by Finii** [comment] 2022-03-03 12:05
Double checked doing the patching, there are no `E`s in the font.

I guess we should put it into the workflow, to always have up to date patched fonts. Guess until now Ryan did this manually.

**Comment by Finii** [comment] 2022-10-11 17:45
Fixed with 801, I guess. Do not know what is in the AUR, but all fonts in the repo do not have the `E`.

**Closed by Finii** 2022-10-11 17:45 UTC
Labels: confirmed
