### ISSUE TITLE
letters of different length

### ISSUE THREAD

**Issue by uvicorn** [ryanoasis/nerd-fonts#566] opened 2021-01-20 14:29 UTC
#### 🎯 Subject of the issue
![изображение](https://user-images.githubusercontent.com/59787538/105188330-5ffadd00-5b66-11eb-9399-d0f3652735e9.png)
in windows term config:
```
      "fontFace": "JetBrainsMono Nerd Font Mono",
```

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ JetBrainsMono Nerd Font Mono
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ Windows terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ windows

**Comment by uvicorn** [comment] 2022-07-14 05:31
0 comments, nice

**Comment by Finii** [comment] 2022-07-14 06:46
> 0 comments, nice

There is no problem statement. `¯\_(ツ)_/¯`

**Comment by uvicorn** [comment] 2022-07-14 07:54
I don't know how to make a problem statement, the letters are of different lengths, I have no idea what it is connected with

**Comment by Finii** [comment] 2022-07-16 11:05
![image](https://user-images.githubusercontent.com/16012374/179352045-028ac066-1bb3-4e97-b9ee-11037202d543.png)

You mean, that in the bottom right at `_DB` the `B` is obviously smaller? And `R` and `T` look a bit too high up?

I remember that on Windows / with Windows Terminal individual glyphs are cached. So this could happen if you use one `JetBrains` and then switch to another font file. That would be fixed by a reboot, though.

Another Idea is that you probably installed the original JetBrains together with the patched one and/or installed multiple patched ones. The font identification stuff (regarding font families) is broken with a lot fonts (PR that fixes it is there). Could be that Terminal confuses different font files.

I guess you rebooted since 2021 ;-) so if the problem is still there we can rule that out.
So could you show which JetBrains* fonts do you have installed (original and NerdFont)?
Also good would be to specify where you got the NerdFont font files from (the link / method)

**Comment by Finii** [comment] 2023-05-05 09:36
The font (family) naming has been fixed in 3.0.0, so this is probably ok now.
If you still experience the problem, please reopen with new screenshot.

To be sure when updating the font (just had that issue with some other font)
* remove old version
* reboot
* install new version

**Closed by Finii** 2023-05-05 09:36 UTC
