### ISSUE TITLE
vertically stretched icons 

### ISSUE THREAD

**Issue by skcc321** [ryanoasis/nerd-fonts#37] opened 2015-09-27 13:43 UTC
Hi there.
What shall I do to fix 'stretching' effect?
example:
![alt text](https://drive.google.com/uc?id=0B0h4JJPKPxpkc0dWOEU2ckRFNnM)
emulator: gnome terminal
font: droid sans mono for powerline plus nerd file types mono 12

Also, I will be very grateful if someone describe how to patch default ubuntu mono font. :)

**Comment by ryanoasis** [comment] 2015-09-29 12:01
This is a known problem and actually I am not sure the best way to make the mono sized glyphs appear big enough without some stretching.

***

In gnome terminal you should be able to use one of the double-width glyph fonts (they won't appear stretched) instead of the true Mono ones. 

For example use `Ubuntu Mono Plus Nerd File Types.ttf` instead of `Ubuntu Mono Plus Nerd File Types Mono.ttf`. They are both Mono the only difference is that the former has some double width glyphs.

***

As for patching your own it should be as simple as:
```
./font-patcher PATH_TO_FONT
```

**Comment by skcc321** [comment] 2015-09-29 12:09
Thx a lot :)

**Comment by MadsRC** [comment] 2016-02-03 15:32
I am experiencing the same thing with my Arch Linux, URxvt, vim+nerdtree and vim-devicons. Font is Sauce Code Pro Complete Mono.

Actually also happens in the i3statusbar, using the same font.

**Comment by Pr0x1m4** [comment] 2016-03-19 15:32
Experienced the same problem
Arch Linux: 4.4.1
Wm: dwm 
Font: Hurmit Medium Complete

Repatching the font without the `--use-single-width-glyphs` or `-s` flag fixed the problem. (In vim as well as statusbar)
![status](http://i.imgur.com/DXXMiXN.png)
![vim](http://i.imgur.com/Iw1qCWI.png)

**Comment by ryanoasis** [comment] 2016-03-19 19:30
@MadsRC @Pr0x1m4 Thanks for the info.

Unfortunately it is a limitation of the script and my knowledge of how to best fix it. The only current alternative as @Pr0x1m4 mentioned is to **not** use the single width glyph version of the font (basically a font name that doesn't end in 'mono'). This also is a WIP to be cleared up (which font do I even want?)

**Comment by s0r00t** [comment] 2016-05-21 11:34
Having same troubles with gVim + patched Hack Regular from the repo. Arch x64 here.
When I'm using the Mono variant as `guifont`, this happens : 
![Stretched](http://i.imgur.com/1jKAdhy.png)

And when I'm using the non-Mono variant, glyphs are cut in two : 
![Cut](http://i.imgur.com/9so6dBA.png)

Weird enough, if I'm pasting long lines of commands in the prompt (ex: `let g:WebDevIconsUnicodeGlyphDoubleWidth = 1`), the icons are fixed : 
![Fix](http://i.imgur.com/mZ3znvq.png)

**Comment by s0r00t** [comment] 2016-05-21 13:06
I just discovered that changing workspaces in i3wm fixes the cut icons... Weird.

**Comment by UFOwl** [comment] 2016-06-02 18:39
Same thing with Windows 10 gVim. 

I download both `Mono Windows Compatible` and `Windows Compatible` (without `Mono`) version, and open them with FontCreator. It seems that icons in former one are half the width of the latter, which making them look 'streched'. However, only the former (`Mono` version) can be recognized by gVim... :(

Finally I replace the icons in `Mono` version with that of the other using FontCreator (just copy and paste), export as a new font, set the new font as `guifont` in `_vimrc` and the problem is solved :) 
![20160603023555](https://cloud.githubusercontent.com/assets/6611701/15756516/2d37b488-2934-11e6-9ff9-52e7867ed128.png)

Hope this helps.

**Comment by ryanoasis** [comment] 2016-06-02 19:47
Nice solution/idea 😄 

Not sure why it would not work in gvim however

**Comment by UFOwl** [comment] 2016-06-03 08:02
The problem (font without `Mono` suffix can't be recognized by gvim) seems font-specific. `DejaVuSansMono` suffers from it while `FiraCode` doesn't. Today I try `Fura Code Regular Nerd Font Complete Windows Compatible` (without `Mono`) and the font successfully shows up in the `Select Font...` menu of gvim, which saves me from modifying it manually:)

**Comment by ryanoasis** [comment] 2016-11-01 03:16
The stretching at least should now be fixed in [0.9.0 branch](https://github.com/ryanoasis/nerd-fonts/tree/0.9.0/patched-fonts).. if anyone would like to try it out

**Comment by ryanoasis** [comment] 2017-03-15 22:59
since [v1.0.0 release](https://github.com/ryanoasis/nerd-fonts/releases/tag/v1.0.0) this is fixed

**Closed by ryanoasis** 2017-03-15 22:59 UTC
Labels: ❲⚖❳glyph sizing
