### ISSUE TITLE
Ioveska Extended Widths

### ISSUE THREAD

**Issue by joshka** [ryanoasis/nerd-fonts#1475] opened 2024-01-05 13:40 UTC
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
Iosevka fonts have Normal and Extended widths in the unpatched font. The extended width is missing in the patched fonts. The extended width matches the normal width of other fonts (Iosevka's normal width is a narrow width).

**Describe the solution you'd like**
Include the extended width in the generated font.

**Describe alternatives you've considered**

**Additional context**

https://typeof.net/Iosevka/

<img width="584" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/381361/43b18cb8-8fea-4b93-9ea5-b8c12381af84">
<img width="618" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/381361/c4e2b556-a67c-4b06-bee6-83ae591f5cd9">

Font selection in iTerm2. Fonts installed via homebrew.

<img width="455" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/381361/02fb74fd-711f-4e5d-8910-7e148bbdcfe7">
<img width="407" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/381361/79d9e89a-17ff-43b4-84aa-a601c981dcc9">

**Comment by Finii** [comment] 2024-01-05 20:02
Thanks for the suggestion!

_Well, Nerd Fonts has no Extended Iosevka in the Nerd Fonts unpatched fonts...:_
_https://github.com/ryanoasis/nerd-fonts/tree/master/src/unpatched-fonts/Iosevka_
_So this is not a bug. Not that you said that_ ;-)

Iosevka has a ridiculous amount of different versions and we only patch a very limited number of them. Still too many for my taste.

Lets assume we add 'extended', in the current setup that means of course with all weights and we have 27 (Italic and Oblique, oh yes), and that for `Iosevka` and `IosevkaTerm`. Luckily for `IosevkaTermSlap` we reduced the number of weights to 15.

That means adding `Extended` equals adding 27+27+15 = 69 fonts.

Maybe self-patching is not too hard? Or only a more limited set of weights?
Hmm :thinking:

**Comment by Finii** [comment] 2024-01-05 20:03
The tag is not really correct, but I believe we have no "extend existing font set" tag.

**Comment by Finii** [comment] 2024-01-05 20:07
If you are an Iterm2 user, is the "use build-in Nerd Font icons" not an option for you, especially if using the nightly build? When I work on Mac this is in fact my go-to option instead of a patched font.

**Comment by joshka** [comment] 2024-01-05 21:31
The iTerm2 feature is not something I was aware of until now. I can't find any docs on it on the iTerm2 site, nor specific settings related to "nerd" in the UI of the stable or beta release. Nightly is probably a bit too bleeding edge for my sensibilities. I can see that there's a couple of refs in the iterm source code to nerd fonts, but can't see an obvious place where the setting surfaces in the UI. What am I missing?

Regardless, my specific situation is from the perspective of a maintainer of a rust TUI library (https://ratatui.rs/). I'm looking for good fonts that work for development of TUI apps. This generally means having good block drawing characters, legacy computing symbols etc, and then Nerd Fonts on top for my day to day use. Fira Code is my go to, but I'd consider Iosevka from time to time. It has better support for the Legacy Computing Symbols block, but I dislike the narrow normal version. Using something that's custom puts me in a place that's not useful for those that use the library.

**Comment by joshka** [comment] 2024-01-06 04:03
Ah found it... that manage special exceptions button:

<img width="243" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/381361/73905893-a4f6-4922-badc-49d15f3d5989">

**Comment by Finii** [comment] 2024-03-24 17:00
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095

**Closed by Finii** 2024-03-24 17:00 UTC
Labels: ❲Aa❳ new font

**Comment by joshka** [comment] 2024-04-22 05:31
> +1 for inclusion of the extended version of Iosevka as I find the default to be too narrow.

Please don't write +1 comments on github like this. Use the thumbs up instead.
