### ISSUE TITLE
JetBrains Mono Regular Nerd Font Complete Mono Windows Compatible.ttf size problems

### ISSUE THREAD

**Issue by francogp** [ryanoasis/nerd-fonts#491] opened 2020-06-16 23:07 UTC
#### 🎯 Subject of the issue

on windows, lots of glyph are shown at the bottom and very small, but in linux, the same are centered and in a correct size.

#### 🔧 Your Setup

- _I'm using 'JetBrains Mono Regular Nerd Font Complete Mono Windows Compatible.ttf' on windows (the problematic font)_
- _I'm using 'JetBrains Mono Regular Nerd Font Complete Mono.ttf' on native linux (just for comparison, but this font seems ok)_
- _Windows Terminal WSL, and Ubuntu 20.04 Distro_ 
- _Windows 10 Pro v2004_

#### ★ Optional
A character example, using windows compatible ttf
![image](https://user-images.githubusercontent.com/2739706/84836305-e0bf8c80-b00b-11ea-884f-b09f8ca193e0.png)

The same character, but on native linux
![image](https://user-images.githubusercontent.com/2739706/84881492-4a6b8500-b064-11ea-9fa8-760ed295e78e.png)

**Comment by francogp** [comment] 2020-06-17 09:33
updated with images

**Comment by cainy-a** [comment] 2020-12-04 21:52
I think this is a similar thing happening here, but for my terminal prompt.
![image](https://user-images.githubusercontent.com/19270622/101218433-fb012b80-367a-11eb-9aa6-4d0b003e90c7.png)
Interestingly is fine on the other side
![image](https://user-images.githubusercontent.com/19270622/101218472-07858400-367b-11eb-9191-f15fef5beea4.png)

**Comment by reportaman** [comment] 2021-02-13 11:21
@francogp In my testing with another font on macOS this happened when I ran [font-patcher](https://github.com/ryanoasis/nerd-fonts#font-patcher) with some ``-s -l`` options. You might want to try generating patched fonts without those options.

**Comment by francogp** [comment] 2021-03-01 10:39
> @francogp In my testing with another font on macOS this happened when I ran [font-patcher](https://github.com/ryanoasis/nerd-fonts#font-patcher) with some `-s -l` options. You might want to try generating patched fonts without those options.

As I said, the font is called "windows compatible", but it fail. That's why I created this issue.

**Comment by brainos233** [comment] 2021-08-01 14:51
I found it'size was correct in https://github.com/ryanoasis/nerd-fonts/commit/4b269b2776969ab87320e853d826a71984d1c3f7

**Comment by andi0b** [comment] 2022-06-10 09:13
I had similar issues in Windows Terminal with the Jet Brains Mono Nerd font. Some characters and numbers were smaller than others, which looked very disturbing.

Removing the Windows Compatible font seems to do the trick. Works with current Windows 10 and Windows Terminal

![grafik](https://user-images.githubusercontent.com/2432095/173033055-eab92e42-dbad-4e50-9bc3-3210c061cde7.png)

**Comment by enticey** [comment] 2022-07-25 11:18
@andi0b experiencing the same issue and deleting the Windows Compatible variant of the font doesn't seem to fix it for me. Really at odds with this since I really like this font and don't wish to change.

**Comment by andi0b** [comment] 2022-07-25 12:29
@enticey: Yes, I had other issues then and ended up patching the font by myself and the resulting ttfs worked like a charm then. I didn't figure out why the builds here don't work.

There is a dockerized version for the nerd font patcher here: https://hub.docker.com/r/nerdfonts/patcher

I attached the fonts I built here, you can try if the work for you, they don't come out of a CI system, so handle with care: [JetBrains Mono Nerd Font.zip](https://github.com/ryanoasis/nerd-fonts/files/9181139/JetBrains.Mono.Nerd.Font.zip)

**Comment by enticey** [comment] 2022-07-25 22:03
@andi0b working beautifully so far, thank you very much! I wonder what the issue is with the initial ones?

**Comment by Finii** [comment] 2022-07-26 11:12
"Windows Compatible" is just about the name(s) of the font. Former versions of Windows (at least I believe it is not present in Windows 10 anymore) limit the font names, maybe to enable a more consistent width in font chooser dialogues?

`Windows Terminal` as very rigid when it comes to glyph sizes. Fonts that work with almost every other application result in strange rendering there. It does not allow glyphs to be larger than what slot size it assumes. If the glyph is larger it is downscaled by `Windows Terminal` in a rather simple (i.e. not smart) way. For that reason you should use the `Nerd Font Mono` variants there.

I do not know if this issue is related to all that. but that just came to my mind. Did not investigate this.

**Comment by Finii** [comment] 2022-07-26 11:19
> For that reason you should use the `Nerd Font Mono` variants there.

Sorry, just notice that you did :grimacing: 

But you use `Windows Terminal`.
And then ... 

I can have a look at this, but that will be some time. Windows problems are not my favorites ;-) (I have no real Windows machine, and this Linux in Windows confuses me completely, how the fonts are supposed to work there...) Feel free to ping again if nothing happens ;)

**Comment by andi0b** [comment] 2022-07-26 12:10
I think I tried the Mono variant too, and it had also issues. Interestingly then it concerned different characters. 

The build here is rather old and also based on an old version of JetBrains mono. Maybe the problem comes from the original font and was fixed there long ago.

**Comment by Finii** [comment] 2022-07-26 12:21
What is also always a problem (for me) with Windows is its font caching stuff. Often I seem to have old glyphs cached and the same font other previously unused glyphs are taken from the newly installed font. I believe that happens on OS level, but it also happens on `Windows Terminal` level, so at least you need to restart Teminal.

Another thing is that Font Grouping is broken in Nerd Font 2.2.0 and previous, that means that strange things can happen if you install more then one font of a group. Do not install all the fancy weights and condensed etc, but limit to 'Regular' and 'Bold' maybe. Which concrete font file is used can be a random gamble, because internally they all have the same name :-(

This just as tips for experimenting. Sorry that I can do more at the moment.

**Comment by andi0b** [comment] 2022-07-30 12:00
I saw that there is now a rather new build of JetBrains Mono inside this repo. But on nerdfonts.com there is still quite an old version linked. I guess most people just download the ZIP from nerdfonts.com, which seems to be utterly broken with Windows Terminal.

Maybe someone can try the current build from here, and check if this is working already: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono

Or maybe even the latest beta-relase from Nov '21 will do the trick: https://github.com/ryanoasis/nerd-fonts/releases/tag/2.2.0-RC

**Comment by andi0b** [comment] 2022-07-30 12:34
So I just tried to figure it out with a new Windows Installation. I used Windows Sandbox with the current stable version of Windows 11 and Windows Terminal, and I couldn't reproduce the issue at all. All font builds i tried just worked without issues.

Maybe the issue got fixed in Windows 11 or some recent Windows Terminal?

**Comment by francogp** [comment] 2022-07-30 21:40
> So I just tried to figure it out with a new Windows Installation. I used Windows Sandbox with the current stable version of Windows 11 and Windows Terminal, and I couldn't reproduce the issue at all. All font builds i tried just worked without issues.
> 
> Maybe the issue got fixed in Windows 11 or some recent Windows Terminal?

Windows 11 you can see this gaps. On linux version, I cant see that.
![image](https://user-images.githubusercontent.com/2739706/181996960-dc22c947-94a9-4a3c-92b7-e4edc84fc2d5.png)

**Comment by Fleshgrinder** [comment] 2022-11-04 16:03
I have size problems on Mac with iTerm 2 between JetBrains Mono and JetBrains Mono NL. Not sure if this is the same issue. 🤔 Ligatures are not enabled, but this actually makes no difference.

<img width="1383" alt="Screenshot 2022-11-04 at 17 01 18" src="https://user-images.githubusercontent.com/1059453/200021932-26755007-e396-496a-bed0-d47236814dde.png">

<img width="1379" alt="Screenshot 2022-11-04 at 17 01 47" src="https://user-images.githubusercontent.com/1059453/200021941-d2117a1d-9ff3-4cf9-9fc9-2f9acbde216b.png">

**Comment by Finii** [comment] 2023-05-01 12:34
Meanwhile we have v3.0.0, maybe try that. Please open new Issue if still problems...

**Closed by Finii** 2023-05-01 12:34 UTC
