### ISSUE TITLE
Add ligatures to font.

### ISSUE THREAD

**Issue by karambaq** [ryanoasis/nerd-fonts#227] opened 2017-12-24 09:29 UTC
Sorry for the noob question, is there a way to add ligatures to font? I'm tried to patch Monaco with -c flag but not see any ligatures.

**Comment by ryanoasis** [comment] 2018-01-11 02:58
@karambaq Hey no worries! :smile: 

There is currently no support for ligatures unless the unpatched font has them. Therefore none of the flags for the patcher have anything to do with ligatures. the "-c" is for a "complete" set of glyphs.

This would be a future improvement for sure but I don't think very easy.

ref: #57

**Comment by ryanoasis** [comment] 2018-01-11 02:59
With that said I am going to close this as a duplicate of issue #57, please subscribe to that issue if you'd like to follow :smile:

**Closed by ryanoasis** 2018-01-11 02:59 UTC
