### ISSUE TITLE
Powerline symbols are not working correctly in Noto Sans Mono

### ISSUE THREAD

**Issue by jethrosun** [ryanoasis/nerd-fonts#347] opened 2019-05-02 04:34 UTC
It appears the powerline symbols are not working correctly in Noto Sans Mono. I am sure because in FuraCode it works fine. 

#### Setup
- Noto Sans Mono Nerd Font Complete
- alacritty
- macOS Mojave

<img width="1657" alt="Screen Shot 2019-05-02 at 12 08 34 AM" src="https://user-images.githubusercontent.com/15823053/57056629-a95c1800-6c71-11e9-8f1c-18b0d457aae7.png">

From the screenshot we can see that the powerline symbols on the right are not working.

**Comment by ryanoasis** [comment] 2019-06-21 04:33
Still have the issue? It looks strange. I see that the glyphs are in the font. Would need someone to try to replicate the issue..

**Comment by jethrosun** [comment] 2019-06-21 13:16
Yes, the problem is still there...

**Comment by jtr860830** [comment] 2020-02-10 07:28
Me either.
My environment is Arch + Gnome Terminal.

**Comment by num3rical** [comment] 2020-05-03 15:24
I'm encountering the same problem. All other Nerd Fonts seem to be working fine with it, just not this one.

**Comment by doraeric** [comment] 2021-12-15 07:07
Spending hours to debug, finally realized it's the font's problem...
My environment is manjaro. It's the default font for gnome terminal.

**Comment by valentino-sm** [comment] 2022-05-14 12:10
Three years passed.
The problem still there.

**Comment by Finii** [comment] 2022-05-14 16:25
Took the [`2.2.0` Release Candidate of Noto]().

Installed `~Downloads/Noto/Noto Sans Mono Regular Nerd Font Complete.ttf`

Font not even selectable in Gnome Terminal (of Ubuntu 22.04), because it is not monospaced.

Installed `~Downloads/Noto/Noto Sans Mono Regular Nerd Font Complete Mono.ttf`

The width is wrong but the right hand side powerline stuff works:

![image](https://user-images.githubusercontent.com/16012374/168440152-ee38ab53-46e3-4461-b62c-747cb94fe7cd.png)

This does not really show what you sayt the problem is.
-> There is a problem with Noto Sans Mono NF (and all Noto iirc), but that is not the powerline symbols missing.

Can it be that you have the `Noto Sans Mono` (unpatched) also installed? Ubuntu has all these 1000 Noto fonts installed, and the first thing I do is removing them all. Because it could be an interaction of `Noto Sans Mono` with `Noto Sans Mono Nerd Font`, unfortunately.

See also
* #610 
* #746

**Comment by valentino-sm** [comment] 2022-05-14 17:30
Thank you for a big review.

> Can it be that you have the `Noto Sans Mono` (unpatched) also installed? Ubuntu has all these 1000 Noto fonts installed, and the first thing I do is removing them all. Because it could be an interaction of `Noto Sans Mono` with `Noto Sans Mono Nerd Font`, unfortunately.

It's not interaction definitely.
I use self-patched fonts on clean arch.
```
python "$srcdir/$_patcher" --glyphdir "$srcdir/glyphs/" -q -c -s {} -out "$srcdir/patched" &> /dev/null ::: "$srcdir/NotoSansMono"/*.ttf
```
Works like a charm. -s flag doesn't make sense

**Comment by Finii** [comment] 2022-05-14 17:53
With interaction between patched and unpatched ... I mean the font grouping. Which is broken in `master`, and terminals can mix up patched and unpatched fonts with the bug :-( There is a PR that fixes the font grouping, forget which one. At least it is in #723 if you specify `--makegroup` when patching.

I still do not know how your issue looks like. Maybe you should add a screenshot.

Fixed the 'too spacy' Noto Mono Blah just now ;-) in #830

**Comment by valentino-sm** [comment] 2022-05-14 22:51
> I still do not know how your issue looks like. Maybe you should add a screenshot.
Exactly the same as first screenshot
Related to all NotoSansMono family
![screenshot_2022-05-15_03-45-09_033905023](https://user-images.githubusercontent.com/5059499/168450471-24a47721-d991-4cac-a9db-bd7b7a0ad21a.png)

**Comment by arebassa** [comment] 2022-07-29 16:19
Does the #830 fix the issue? If it does, can I download the patched font from somewhere or do I have to build it myself?

Cheers!!

**Comment by Sebasos01** [comment] 2023-02-02 16:57
I have this same problem using Alacritty on Arch Linux + KDE, I installed with pacman powerline and with yay (from the AUR) powerline-fonts-git. 
Noto Sans (KDE's default font, at least in my case) makes the powerline "triangles" smaller.
[](https://i.ibb.co/jhprWZY/Screenshot-20230202-114529.png)
Using the "Noto Mono for Powerline" font solves the problem, although it is not my favorite font.
[](https://i.ibb.co/Bsk8wzJ/Screenshot-20230202-114446.png)
At the moment I have not found something like "Noto Sans for Powerline".

**Comment by Sebasos01** [comment] 2023-02-02 17:14
I have this same problem using Alacritty on Arch Linux + KDE, I installed with pacman powerline and with yay (from the AUR) powerline-fonts-git.
Noto Sans (KDE's default font, at least in my case) makes the powerline "triangles" smaller.
![Screenshot_20230202_121314](https://user-images.githubusercontent.com/69820701/216394967-9ba4c5ff-c2b8-4cc1-93ea-bf82e3bed7f5.png)
Using the "Noto Mono for Powerline" font solves the problem, although it is not my favorite font.
![Screenshot_20230202_121335](https://user-images.githubusercontent.com/69820701/216395025-7c7a303f-5565-4cef-b425-d8dc713f9b2a.png)
At the moment I have not found something like "Noto Sans for Powerline".

**Comment by Finii** [comment] 2023-02-02 17:15
@Sebasos01 

The upper image shows that you use an unspecified font. I guess it is **not** a Nerd Fonts font.
That font does not have individually scaled powerline symbols in it, so they are taken from some other font.
The mix of two different fonts might not mix well.

You can check this (please reply with result) via
```
$ fc-list ':charset=e0b0'
```

At least that is a theory.

You also do not specify _which_ Nerd Font you installed. All Nerd Fonts are now in Arch Community, do not use the Nerd Fonts from AUR (they are most likely obsolete).

* Please give package name and version with the Nerd Font you wanted to use
* Enter the family name of that font into your `alacritty` config
* Start via `alacritty -vv` and show reasults

**Comment by Finii** [comment] 2023-02-02 17:20
You probably want this package:
https://archlinux.org/packages/?sort=&repo=Community&q=-nerd+noto&maintainer=&flagged=

If you do not have that installed, install it.
Use that font family name specifically in your `alacritty` conf, do not leave it empty.

**Comment by Finii** [comment] 2023-02-02 17:22
@arebassa Just install the Nerd Fonts `v2.3.3` release, it should be fixed.

**Comment by Sebasos01** [comment] 2023-02-03 00:21
@Finii Thanks, that package worked for me. I also installed other packages from the Arch Community and they also work fine. The problem was that I didn't know how to find the font family name lol, but it was just checking the output of fc-list ':charset=e0b0', which by the way there I could see that I have the "Noto Mono for Powerline" font and several other "for powerline" fonts in ~/.local/share/fonts, at some point I must have installed them but I don't remember. Thanks again.

**Closed** 2023-02-04 11:44 UTC
