### ISSUE TITLE
Only Fira Code works with my VS Code, no other font works

### ISSUE THREAD

**Issue by technofantods** [ryanoasis/nerd-fonts#332] opened 2019-03-11 22:28 UTC
I was told to post this issue in here.

#### 🎯 Only Fira Code Nerd Font will work with my install of VS Code

if i enter any font other than Fira Code... i don't get any ligatures. I'd prefer to use Hack. I have every font installed on my system

I am prob missing something really simple. I appreciate anybody's help.

#### 🔧 My setup

- Fira Code but want to use Hack in the editor.
- Hack works in the Terminal (see screenshot)
- VS Code editor and VS Code terminal
- Ubuntu... KDE... Ubuntu 18.04.2 LTS

#### ★ Optional

attached a pic of my VSCode JSON settings... showing Powerline font working in terminal. I'm using Fira but all ligatures break if i use any other Nerd Font.

Thanks in advance for any help.
If I should take this to Gitter, that's not a problem.

screenshot:
![Screenshot_20190311_182314](https://user-images.githubusercontent.com/37778164/54162123-cd963800-442a-11e9-9adb-b5e03f9173f9.png)

**Comment by ryanoasis** [comment] 2019-03-12 04:40
Thanks for the report. Nope this is better than Gitter for something like this

**Comment by chrissimpkins** [comment] 2019-03-13 12:20
[This VS Code IR post](https://github.com/Microsoft/vscode/issues/192#issuecomment-319999511) suggests that your settings are correct.  

The only other related settings that I've come across are these https://github.com/Microsoft/vscode/pull/1510#issuecomment-166968687

**Comment by technofantods** [comment] 2019-03-16 20:29
Hey Thanks... at least my settings are correct.

I will try to setup Hack with Sublime Text, VIM & Hyper and see how that all works out... I appreciate the help very much.

Thank you!
B

**Comment by ryanoasis** [comment] 2019-08-11 23:58
Any updates @technofantods ?

I am going to close this issue for now, please feel free to re-open or follow-up if the issue is with Nerd Fonts :smile:

**Closed by ryanoasis** 2019-08-11 23:58 UTC

**Comment by aasutossh** [comment] 2020-07-07 03:10
I am facing this exact issue. I am using Win 10. Installed fonts using scoop (#223). I mainly used Iosevka before (on Linux), so I wanted to use it. I installed bunch of others like VictorMono, agave, FiraCode. Out of them all only FiraCode works in VS Code. Victor Mono works in Hyper.is but agave, Iosevka-NF doesn't. I don't seem to understand what the issue is, or how it was fixed before.

**Comment by edoardoc** [comment] 2020-09-27 16:56
Hello, 

just tried to set Terminess and Courier Prime from nerd font. none works on win 10, going back to fira :/

**Comment by aasutossh** [comment] 2020-09-28 02:26
So, what worked for me is download the original font and then patching yourself using the font-patcher script. And change the name of the font using something like https://github.com/chrissimpkins/fontname.py.

**Comment by chrissimpkins** [comment] 2020-09-28 13:40
> So, what worked for me is download the original font and then patching yourself using the font-patcher script. And change the name of the font using something like https://github.com/chrissimpkins/fontname.py.

This suggests to me that it is an issue with the OpenType name tables.  I took a look at the patched agave and found the following issues:

- **nameID2**: subfamily should be the name of a RIBBI style or weight, currently defined as "r" which is not per OT spec (definitely a candidate for the inability to register in OS's/apps)
- **nameID4**: should be the concatenated strings from nameID 1 (family) and 2 (subfamily) (definitely a candidate for the inability to register in OS's/apps)
- **nameID5**: version string spec states that the format should be "Version [number < 65,535].[number < 65535]".  Any other character after that string terminates the version string spec and you can use any string thereafter.  You'll find apps like ttfautohint use the "after version string section" of nameID5 for metadata.  Unclear to me if/where this is an issue.  I've seen many projects that do not use this version string formatting. Likely lower priority fix than the previous records in the name tables.
- **nameID16**: extended typographic family name.  looks like this is defined as "r" which is being used as a style string in this build
- **nameID17**: extended typographic subfamily name. has fewer restrictions than the RIBBI only nameID2 and intended for families that extend beyond regular, bold, italic, bold italic styles.  This should be a *subfamily* name.  Currently defined as "type agaric: agave regular"

In the current Fira Code build, all of the above appears to be valid with the exception of nameID 4 which is not the concatenated nameID 1 + 2 (i.e., Regular should be the tail of the string).  If Fira Code is functioning in editors, by process of elimination you might edit agave nameID 2 to "Regular" (or appropriate style if there are multiple), update nameID 4, and eliminate nameID 16, 17 in order to see if it works.

If you run a project like [fontbakery](https://github.com/googlefonts/fontbakery/) over the builds, it may point out some of these OT spec issues.  I've released [this GitHub Action](https://github.com/f-actions/font-bakery) as a quick fontbakery CI GH Action config if it happens to be useful to you.  

A couple of references for anyone who wants to dive in on the spec:

- [MS OT spec, name tables, nameID's](https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids)
- [MS OT spec, example name strings](https://docs.microsoft.com/en-us/typography/opentype/spec/namesmp)
