### ISSUE TITLE
Hurmit font(s) glyphs distorted

### ISSUE THREAD

**Issue by LNQ** [ryanoasis/nerd-fonts#74] opened 2016-03-24 19:51 UTC
Hi, tried the Hurmit complete mono light orf font and found the powerline glyphs pretty messed up.
Other glyphs look distorted also.
See screenshots.

![2016-03-24-203656_998x356_scrot](https://cloud.githubusercontent.com/assets/7047368/14029233/417d2942-f201-11e5-8047-cc075ebfaff7.png)

![fontforge](https://cloud.githubusercontent.com/assets/7047368/14029116/90d89f18-f200-11e5-957f-cdffac5749ff.png)

**Comment by ryanoasis** [comment] 2016-03-24 23:46
Hey, thanks for the report. :+1: 

Sorry this is a bit of a pain point at the moment. :cry: 

I really need an automated script to generate previews for the various fonts to help me test them. :grin:

**Comment by ryanoasis** [comment] 2016-05-15 18:54
In the latest release ([v0.8.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v0.8.0)) the merge (e0a0), line number (e0a1), and lock (e0a2) glyphs should now be proper (because it is using the glyphs from the original font).

The others still have issues because of the EM sizes which I have yet to address, sorry.

**Comment by ryanoasis** [comment] 2016-11-01 02:42
@LNQ This should be fixed with the [fonts in 0.9.0 branch](https://github.com/ryanoasis/nerd-fonts/tree/0.9.0/patched-fonts). Feel free to try it out and thanks :smile:

**Comment by ryanoasis** [comment] 2017-02-20 15:39
Re-confirmed that this has since been fixed (updating ticket):

![selection_002](https://cloud.githubusercontent.com/assets/8083459/23131565/7a737154-f758-11e6-929b-5ee2b039aa5b.png)
![selection_003](https://cloud.githubusercontent.com/assets/8083459/23131677/df1d28fc-f758-11e6-8ef0-f56581c74109.png)

**Closed by ryanoasis** 2017-02-20 15:39 UTC
Labels: ❲⚖❳glyph sizing
