### ISSUE TITLE
Bump up Monaspice version from 1.000 to 1.101

### ISSUE THREAD

**Issue by Daverd-GM** [ryanoasis/nerd-fonts#1661] opened 2024-06-19 23:55 UTC
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

The font Monaspace contained in Nerd Fonts is still on version 1.000

Expected behavior:

Nerd font Monaspice should be based on version 1.101 they significantly revamped the way ligatures work with the Stylistics Sets on [1.100](https://github.com/githubnext/monaspace/releases/tag/v1.100) and [1.101](https://github.com/githubnext/monaspace/releases/tag/v1.101)

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   MonaspiceArNerdFont-Regular.otf
   MonaspiceKrNerdFont-Regular.otf
   MonaspiceNeNerdFont-Regular.otf
   MonaspiceRnNerdFont-Regular.otf
   MonaspiceXeNerdFont-Regular.otf
   and the other variants
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   -    https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Monaspace.zip
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   -    Windows Terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   -  Windows 11 Versión 23H2 (compilación de SO 22631.3737)

**Comment by Finii** [comment] 2024-06-20 04:28
Duplicate of
* #1630

<img width="1052" alt="Screenshot 2024-06-20 at 06 27 51" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/d07bf936-aa7d-46fa-9b4c-e5a099c924ac">

Monaspice will be updated on the next Nerd Fonts release, i.e. `v3.3.0`.
Rough estimate would be September.

You can easily self-patch the current version if need be. Please read the readme.md for that, or ask for more help here.
If you self-patch, you need to additionally specify `--makegroups 4`, see its [`config.cfg` ](https://github.com/ryanoasis/nerd-fonts/blob/master/src/unpatched-fonts/Monaspace/config.cfg).

**Closed by Finii** 2024-06-20 04:28 UTC
