### ISSUE TITLE
Some glyphs missing after v3.x.x update

### ISSUE THREAD

**Issue by luizkowalski** [ryanoasis/nerd-fonts#1190] opened 2023-05-01 19:10 UTC
#### 🗹 Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
this morning I updated some deps on my computers and some fonts were updated as well but this is not a big deal since this has happened before, but after the update finished I noticed some icons on my neovim were wrong like the `Gemfile` icon and the `X` for closing a buffer:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/112706/235512942-fddd3422-635a-46a7-a0b0-47e2e488ce54.png">

This was weird so I decided to delete all custom fonts I had, clean up the cache, re-download them manually, and reinstall it. To my surprise, nothing has changed

No idea what is going on, this is my text configuration on iTerm2:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/112706/235512978-8d14b991-fa6e-406b-9499-36a84f26b275.png">

Neovim version:

```
:version
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"
```

No Neovim config has been changed prior to today or after this.

Expected behavior:
X and missing icons should exist

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Fira Code Nerd Font and Fira Code Nerd Font Mono
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Homebrew and manually download
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - iterm2
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   -  MacOS

One more screenshot from other missing icons

<img width="554" alt="image" src="https://user-images.githubusercontent.com/112706/235514769-b6bebf10-614a-46f7-8663-b53ddb3fb3e9.png">

I guess it should've been the "unknown file" icon

**Comment by Finii** [comment] 2023-05-01 19:39
Can you try to copy and paste the missing-icon-characters into a comment as text here? I can determine the codepoints then.

**Comment by dbuch** [comment] 2023-05-01 19:39
Right, I can confirm this problem.

> Which font are you using (e.g. Anonymice Powerline Nerd Font Complete.ttf)?

Fira Code Nerd Font and Fira Code Nerd Font Mono

Same here.

> Are you using OS X, Linux or Windows? And which specific version or distribution?

Linux (Arch linux)

**Comment by Finii** [comment] 2023-05-01 19:44
I fear the missing icon are from the dropped Material Design Icons set. But we need the codepoints or the characters copy as text an pasted into a comment to see.

I also use neovim, I have never seen that gui-ish thing, what is the command to activate that?

**Comment by luizkowalski** [comment] 2023-05-01 19:46
Couldn't copy but I guess I managed somehow to see some info when right-clicking with the mouse:

This one is the `.rbi` file, probably missing icon
<img width="308" alt="image" src="https://user-images.githubusercontent.com/112706/235518526-8255e837-b4ae-416b-bcdf-93151513a28f.png">

This one was the close button:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/112706/235518665-5597f9f5-e096-40b8-a3fc-8bef03a6fbfe.png">

> I have never seen that gui-ish thing, what is the command to activate that?

That would be Telescope with `git_files` command

**Comment by luizkowalski** [comment] 2023-05-01 19:47
Also, noticed that .svg files have this weird icon that looks like something in Arabic?
<img width="313" alt="image" src="https://user-images.githubusercontent.com/112706/235518928-e40303e2-eccf-483e-8d02-4075095699e1.png">

<img width="144" alt="image" src="https://user-images.githubusercontent.com/112706/235518950-3be93083-d70d-469c-8691-9fc0c910c9fd.png">

**Comment by Kedap** [comment] 2023-05-01 21:07
I think it's a problem with the icon pack like 'neovim-web-devicons' or packages like that. Something similar happens to me but with cascadia code (original) and also with fira code (Fira Code Nerd Font). In the first case I thought it was just a cascadia code error, so I installed CaskaydiaCove but the problem persists. This all started this morning when I decided to update, which is the same archlinux.

![firacode_alfa_error](https://user-images.githubusercontent.com/48705030/235529587-f2304181-57cc-49cb-8e0c-191e186ca110.png)

![Captura de pantalla_2023-05-01_15-00-28](https://user-images.githubusercontent.com/48705030/235530501-7da4a652-df15-428c-8e3d-42fb4bf6b9a0.png)
![CaskaydiaCove NFM error](https://user-images.githubusercontent.com/48705030/235529604-03d0ab3b-ea5b-4d47-879e-561f4b1c3d7c.png)
**nf-mdi-format_size** error render
![Captura de pantalla_2023-05-01_14-56-35](https://user-images.githubusercontent.com/48705030/235529835-b7948bf1-cf47-44f2-b0d2-911acb6790c6.png)
The deprecated tag seems to indicate something

This is the same with other icons. But something curious is that Caskaydia is installed in kitty and FiraCode in wezterm and with wezterm if I can see the second icon
![text](https://user-images.githubusercontent.com/48705030/235531061-0e9de952-aa96-40a5-8cf6-c8b6048f7c88.png)

I think a lot of popular icons are marked as deprecated and therein lies the problem. As far as I see what happens, I will continue to regret updating :(

**Comment by luizkowalski** [comment] 2023-05-01 21:12
oh, good find! yeah, the X icon (F655) is obsolete too, which proves your point

**Comment by Kedap** [comment] 2023-05-01 21:12
https://github.com/onsails/lspkind.nvim/pull/64

**Comment by luizkowalski** [comment] 2023-05-01 21:24
there is a PR for it already on nvim tree devicons too: https://github.com/nvim-tree/nvim-web-devicons/pull/264

**Comment by Finii** [comment] 2023-05-02 07:31
> Also, noticed that .svg files have this weird icon that looks like something in Arabic?

See 'reason' above. That codepoint IS the codepoint for that Arabic glyph. Imagine you want to write something and instead of the expected glyph (equivalent to letter `A`) you get some weird icon.

Well, I hope you will not be too angry and frustrated, understanding the reason. Nerd Fonts got that unfortunately wrong from the start, and at some point in time we should stick to the standard.

> This one is the `.rbi` file, probably "unknown file" icon

Where does the `rbi`file come from (which project)? Some plugin? We should raise an issue there.

**Comment by Finii** [comment] 2023-05-02 07:33
To help more we could show the replacement codepoint in the cheat sheet. Would that help?

But sometimes the updated MDI looks different (well that is the reason for the MDI update), or has been dropped completely meanwhile.

**Comment by luizkowalski** [comment] 2023-05-02 07:48
> Where does the rbifile come from (which project)? Some plugin? We should raise an issue there.

[Ruby's Sorbet file type](https://sorbet.org/docs/rbi). Developers don't really touch this file, it is autogenerated and you are highly encourage to leave like this, that's why, personally, never bothered me the unknown file

**Comment by luizkowalski** [comment] 2023-05-02 08:55
@rj1 if I understand correctly (and Finii can correct me if I'm wrong cause I'm just learning all of this), it is not a Nerd Font's issue. It was announced previously that Material Icons (probably the missing symbols you are seeing) were to be deprecated due to them not being free. if anyone is to blame, is whatever library you are using to render these symbols (e.g. vim's devicons). You should go to their repository and check open issues

**Comment by Finii** [comment] 2023-05-02 09:04
> it is not a Nerd Font's issue

Well, it kind of is, but is `not-a-bug`. The symbols needed to change their codepoints.

> deprecated due to them not being free

The icons were free and they are still there, but the codepoints were not free, they are needed for non-latin texts. To occupy codepoints that are not free-to-use has been an oversight years ago when non-latin texts were not a consideration.

> You should go to their repository and check open issues

Definitively. Or raise an issue there. Link to this thread in your report there.

**Comment by Finii** [comment] 2023-05-02 09:17
## Collection of helper projects

https://github.com/loichyan/nerdfix
https://gist.github.com/mischw/78e8e42c2ebb1069560a2fc4573b1425

**Comment by rj1** [comment] 2023-05-02 09:22
thx!

in my case it's just some symbols i've pasted from https://unicodes.jessetane.com/ into my neovim config 

@mischw's [python script](https://gist.github.com/mischw/78e8e42c2ebb1069560a2fc4573b1425) is v helpful & managed to get most of them, but there's still a couple that either don't render or render something completely different than before :(

柳 

**Comment by rootex-** [comment] 2023-05-02 12:37
I can also confirm the problem:
<img width="960" alt="Screenshot 2023-05-02 at 15 35 33" src="https://user-images.githubusercontent.com/8237030/235667635-3b5c2b3f-29c9-4803-aa75-fade1f9b8ba7.png">

To compare it with another working font:
<img width="750" alt="Screenshot 2023-05-02 at 15 36 32" src="https://user-images.githubusercontent.com/8237030/235667813-d0fedeaa-c87a-4810-b5ab-8caffd00dc91.png">

**Comment by rootex-** [comment] 2023-05-02 13:00
[nerdfix](https://github.com/loichyan/nerdfix) utility has helped me to find missing symbols and replace them by hand

**Comment by siduck** [comment] 2023-05-03 08:23
hi @Finii  is this folder icon removed?

 
![image](https://user-images.githubusercontent.com/59060246/235865321-750637d5-54b7-471e-b3b2-b0659556a713.png)

Copy it from site gives me another icon ( cuz the site isnt updated to v3.0 ) 
![image](https://user-images.githubusercontent.com/59060246/235865651-389c4fea-9c71-4ab1-bfe7-ea2ea9079e67.png)

But i wasnt able to find it by fontforge too

**Comment by Finii** [comment] 2023-05-03 09:27
They (octicons) obviously modernized/updated that glyph...
We updated to the latest octicons with v3.0.0

![image](https://user-images.githubusercontent.com/16012374/235879839-e0994e20-4d09-4ed6-8db2-75a13287dd52.png)

**Comment by musjj** [comment] 2023-05-03 09:40
Are you sure that's _just_ a modernized version? For example, the icon in the 4th column of the 2nd row, I can't imagine that the old and new version serves the same purpose.
![image](https://user-images.githubusercontent.com/72612857/235882615-75071db1-ac17-4122-800d-93502fde75f1.png)

**Comment by Finii** [comment] 2023-05-03 10:04
Some icons have been dropped without replacement. We 'compress' the glyph-map, so that newly added icons fill up the gaps. Otherwise we would run out of codepoints rather soon.

Here the update process log
```
Reading mapping file
Found 172 entries
Fetching octicons archive "v18.2.0.tar.gz"


Unpacking octicons archive
Found 574 svgs
Found 308 icons after de-duplicating

Renamed cloud-download -> download
Renamed cloud-upload -> upload
Renamed clippy -> paste
Renamed mail-read -> read
Renamed primitive-dot -> dot-fill
Renamed primitive-square -> square-fill
Renamed settings -> sliders
Renamed dashboard -> meter
Renamed trashcan -> trash
Renamed paintcan -> paintbrush

Missing octoface
Missing keyboard
Missing gist
Missing file-text
Missing file-pdf
Missing jersey
Missing radio-tower
Missing repo-force-push
Missing mail-reply
Missing arrow-small-right
Missing gist-secret
Missing no-newline
Missing arrow-small-up
Missing arrow-small-down
Missing arrow-small-left
Missing file-symlink-directory
Missing circuit-board
Missing watch
Missing text-size
Missing ellipses
Missing plus-small

Found 151 (of 172, missing 21) and new 157
```

Obviously `keyboard` has been dropped and we fill/reuse it's space with some newly added icon.
See also #1156

**Comment by siduck** [comment] 2023-05-03 11:19
> They (octicons) obviously modernized/updated that glyph... We updated to the latest octicons with v3.0.0
> 
> ![image](https://user-images.githubusercontent.com/16012374/235880492-33ff3fc6-8df6-4b19-a575-5b9e8692ae34.png)
> 
> _Edit: Changed to more meaningful image_

oh didnt know, but fr the icon barely looks modernized! No idea why they replaced the folder icon with an empty folder icon :(

**Comment by siduck** [comment] 2023-05-04 03:16
> They (octicons) obviously modernized/updated that glyph... We updated to the latest octicons with v3.0.0
> 
> ![image](https://user-images.githubusercontent.com/16012374/235880492-33ff3fc6-8df6-4b19-a575-5b9e8692ae34.png)
> 
> _Edit: Changed to more meaningful image_

Can I make a new font with just the file-directory icon and set different endpoint for it? is this possible

**Comment by musjj** [comment] 2023-05-04 06:01
There's a couple filled versions of the folder icon around the bottom right. Maybe use that?

**Comment by siduck** [comment] 2023-05-04 06:43
> There's a couple filled versions of the folder icon around the bottom right. Maybe use that?

I know that but I want this one only specifically, it looks good. 

Atom used to use it, doom emacs uses it too

![image](https://user-images.githubusercontent.com/59060246/236129366-957e6397-90d4-4b84-b9e9-b1a281eb602d.png)

I've used it in my nvim config as well 

![image](https://user-images.githubusercontent.com/59060246/236129616-c8a9f43c-5272-4719-92b0-f8a6d6f28320.png)

**Comment by Finii** [comment] 2023-05-04 10:57
Updated the cheat-sheet to (hopefully) communicate in a more clear way what happened:

![image](https://user-images.githubusercontent.com/16012374/236184036-c8fad8b9-8d35-41bc-bb3a-e232e173e898.png)

This is how it looks like when following the example in the bottom, to find out where a removed glyph moved to:

![image](https://user-images.githubusercontent.com/16012374/236184384-978dbecc-4595-430d-b1dc-63bc70e2841f.png)

And if you enter a codepoint you can see old and new content side by side (because the cheat-sheet secretly also loads the v2.3.3 font to be able to show the removed icons):

![image](https://user-images.githubusercontent.com/16012374/236184703-cc268525-b286-4922-b130-e355b0964bbc.png)

Hope this helps.

**Comment by thyeun** [comment] 2023-05-06 14:07
After recent update, a branch of font change into chinese words, as you can see below.

![Screenshot_2023-05-06-21-59-07_3658](https://user-images.githubusercontent.com/1939446/236629033-9b1d1132-c260-42df-87b4-d70fa85beaa3.png)

**Comment by Finii** [comment] 2023-05-07 07:14
> After recent update, a branch of font change into chinese words, as you can see below.

@thyeun Great! So it does work! Finally we freed the Chinese words and one can write correctly. (I.e. this is wanted and needed and not a bug)

You probably need to follow the codepoint movement with your setup; there are several hint above.

**Comment by yakomisar** [comment] 2023-05-10 08:35
@thyeun

### How to fix broken icons in JetBrains Mono Nerd font.
_My font - JetBrains Mono Nerd font._

If you encounter a broken icon in JetBrains Mono Nerd font, follow these steps:

1. Find the broken icon, which is usually marked with a ? in a rhombus, ? in a square, or just a ? mark. For example:
<img width="1198" alt="Снимок экрана 2023-05-10 в 10 37 10" src="https://github.com/ryanoasis/nerd-fonts/assets/20434122/a026898b-f9d0-4ded-a817-40873143eb9e">


2. Go to the Nerd Fonts Cheat Sheet and locate the icon you want to use. Click on the "Copy UTF" button to copy the Unicode character code for the icon. Note that even if an icon is not marked as obsolete, it may still not work as expected. To check the visibility of the icon, proceed to step 3.
<img width="339" alt="Снимок экрана 2023-05-10 в 11 08 45" src="https://github.com/ryanoasis/nerd-fonts/assets/20434122/0800cd62-a9d0-4d8a-ae05-49eda5f2f6a8">

3. Check the visibility of the icon using the following command in the terminal:

`echo -e "\<your copied utf code>`

Replace "<your copied utf code>" with the Unicode character code for the icon you want to use. If the icon is visible and appears correctly, you can use it in your script or configuration file.
<img width="321" alt="Снимок экрана 2023-05-10 в 11 24 55" src="https://github.com/ryanoasis/nerd-fonts/assets/20434122/a1b62670-e476-4efb-a24e-12f7ba6236a7">

4. Copy and paste the icon from the terminal wherever you want to use it.

5. Enjoy your fixed icons!

**Comment by thyeun** [comment] 2023-05-10 08:45
@yakomisar thanks, but i have better solution instead that using codepoint and check one by one from cheatsheet. 

:)

**Comment by lazzzaroni** [comment] 2023-05-11 09:29
Hi everyone!
Can you help me to find proper replacement for this icons? It seems that they aren't properly scaled anymore for vim/tmux configs.

This is what I have with MesloLGS Nerd Font Mono 3.0:
![image](https://github.com/ryanoasis/nerd-fonts/assets/68731150/2f00ff9a-a26d-4908-b832-e65496ffe522)

This is how it should look:
![image](https://github.com/ryanoasis/nerd-fonts/assets/68731150/ea1c17f8-24d7-4a4e-b348-e8be4d669c3c)

Here are the glyphs that don't work correctly anymore:



To be more precise, here's the theme which have this bug after moving to NF 3.0: https://github.com/jimeh/tmux-themepack/tree/master

Maybe someone already solve this problem? 

Cheers!

**Comment by siduck** [comment] 2023-05-11 10:20
> Hi everyone! Can you help me to find proper replacement for this icons? It seems that they aren't properly scaled anymore for vim/tmux configs.
> 
> This is what I have with MesloLGS Nerd Font Mono 3.0: ![image](https://user-images.githubusercontent.com/68731150/237637354-2f00ff9a-a26d-4908-b832-e65496ffe522.png)
> 
> This is how it should look: ![image](https://user-images.githubusercontent.com/68731150/237637523-ea1c17f8-24d7-4a4e-b348-e8be4d669c3c.png)
> 
> Here are the glyphs that don't work correctly anymore:  
> 
> To be more precise, here's the theme which have this bug after moving to NF 3.0: https://github.com/jimeh/tmux-themepack/tree/master
> 
> Maybe someone already solve this problem?
> 
> Cheers!

Try https://github.com/loichyan/nerdfix

**Comment by thyeun** [comment] 2023-05-11 10:36
@lazzzaroni are you using arch linux? if yes, there have a repos for the nerd font complete v2.2, it work for me to get back all the font i need.

**Comment by Finii** [comment] 2023-05-11 12:10
> Here are the glyphs that don't work correctly anymore:  

`E0B0` etc are off-topic here. I move this to another topic.
They have not changed codepoints. The problem looks like wrong scaling instead.

**Comment by saikete** [comment] 2023-05-20 07:59
As a novice, I followed the Nvchad official documentation to install
nerdfont, and then enabled Nvchad in the iterm2 terminal and made some my own configurations, and then there were problems such as the search icon not appearing, but the problem did not occur in the GUI, and I felt that it might be some configuration in iterm2 problem, but I haven't found a solution so far. . .
<img width="492" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/45237450/e537c749-7b51-4547-b374-0fdc0db0afcc">
<img width="415" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/45237450/c2adba7f-3ade-44a2-b73b-7b4124213540">
<img width="943" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/45237450/755824d3-e379-4304-bc68-324b322ce901">

**Comment by thyeun** [comment] 2023-05-20 08:17
@saikete You missing out of the search glyph? i replace that with the ```e68f```, original search glyph ```f002``` always given issue after each time new update. 

And one thing to check with you, are you using same font for your GUI and Nvim?

**Comment by saikete** [comment] 2023-05-21 06:08
I think replacing characters manually is a lot of work, which is fine when there are few characters, but not a good solution when there are quite a lot of wrong characters

My GUI is using neovide. In fact, I have not confirmed what font is used by the GUI without setting the font! According to my understanding, the default font of the terminal should be used? I'm not sure about this. Another reason why I don't use the terminal now is that I can't capture the <A-i> key. I use mac+hhkb, so I will miss a lot of interesting keys. I have submitted an issue: https://github .com/neovide/neovide/issues/1867, in short, I am still confirming where the problem is that the font is difficult to display,,,

**Comment by Finii** [comment] 2023-05-26 07:43
@saikete 

> I think replacing characters manually is a lot of work, which is fine when there are few characters, but not a good solution when there are quite a lot of wrong characters

Maybe one of the [helpers](https://github.com/ryanoasis/nerd-fonts/issues/1190#issuecomment-1531147557) can be used?

**Comment by wez** [comment] 2023-05-29 02:58
Sort of related to this, in wezterm, there is automation that scrapes the name -> symbol mapping from the various scripts in https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/lib so that we can provide lua constants for them.
After updating to 3.0.1 the various mdi symbols were stale because we read in https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/lib/i_material.sh instead of https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/lib/i_md.sh

It would be great if you could consider removing i_material.sh if it is no longer an accurate mapping!

(BTW: I'd love it if there was a json blob or similar that held the definitive mapping in a machine readable structure!)

**Comment by saikete** [comment] 2023-06-01 08:43
> 与此相关，在 wezterm 中，有一种自动化功能可以从https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/lib中的各种脚本中抓取名称 -> 符号映射，以便我们可以为他们提供lua常量。 更新到 3.0.1 后，各种 mdi 符号已过时，因为我们在https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/lib/i_material.sh而不是[https://github 中读取.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/lib/i_md.sh](https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/lib/i_md.sh)
> 
> 如果您可以考虑删除 i_material.sh，如果它不再是一个准确的映射，那就太好了！
> 
> （顺便说一句：如果有一个 json blob 或类似的东西在机器可读结构中保存最终映射，我会很高兴！）

Sorry it took me a while to understand what you said, so first off, I'm using the iterm2 terminal, should I replace wezterm? I don’t have the .sh script you mentioned locally. Should I go through the document carefully so that I can delete the i_material.sh script?

**Comment by saikete** [comment] 2023-06-01 08:45
> @saikete
> 
> > I think replacing characters manually is a lot of work, which is fine when there are few characters, but not a good solution when there are quite a lot of wrong characters
> 
> Maybe one of the [helpers](https://github.com/ryanoasis/nerd-fonts/issues/1190#issuecomment-1531147557) can be used?

Thank you very much for your suggestion, I will follow a more reasonable way to solve my problem, and at the end I will read the document carefully to complete the operation you said

**Comment by wez** [comment] 2023-06-01 12:38
@saikete my comment was directed towards the nerd fonts maintainers, not to you specifically!

**Comment by Finii** [comment] 2023-06-01 15:55
@wez 

> It would be great if you could consider removing i_material.sh if it is no longer an accurate mapping!

Well, it is used for the "removed" icons on the Cheat Sheet. Of course we could put it somewhere else, but...

> I'd love it if there was a json blob or similar that held the definitive mapping in a machine readable structure!

Is https://github.com/ryanoasis/nerd-fonts/blob/master/glyphnames.json not suited? That is intended just for what you want to do.

It the moment the `i_*.sh` are 'the database' of the glyph names. Some of these shell scripts are autogenerated, some were manually tweaked. From that files all other collections of names come. For example the glyphnames file and the cheat sheet, as well as the css files. If that is a good solution? It is just how it grew historically.
But I believe with the json file everyone can work? If we need an expansion in fields or something just tell me.

**Comment by Finii** [comment] 2023-06-02 06:23
@wez 

> there is automation that scrapes the name -> symbol mapping from the various scripts

If you want to stick to that, I would suggest using (i.e. executing) the `i_all.sh`, as that will not return the removed icons (unless asked to). The information `i_all.sh` collects can then be automated further, see https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/generate-css.sh as example.

But I guess glyphnames.json is even better for you.

**Comment by Finii** [comment] 2023-06-05 10:13
@allcontributors add @loichyan for tool

**Comment by Finii** [comment] 2023-06-05 10:17
@allcontributors add @loichyan for tool

**Comment by cabiamdos** [comment] 2023-07-04 17:29
Hello guys, I have here a patch-solution that I have implemented (https://github.com/cabiamdos/nerd-fonts-fix). Hope it is useful. Basically I have remapped the available theme icons (unicodes) into the ones that are in the fonts.

**Comment by jpcercal** [comment] 2023-07-07 20:08
I've been using nerdfonts with zsh + starship + iTerm2, thanks for the great work everyone!

`nerdfix` managed to solve the problem, I had only one file that had to be patched as it can be seen below. 

`./nerdfix fix ~/dotfiles/starship.toml`:

```
# Auto fix it using last input '󰇁'
note: Found obsolete icon U+FA1E
    ┌─ /Users/jpcercal/dotfiles/starship.toml:128:12
    │
128 │ format = "[羽](bold cyan)[took $duration](bold cyan) [❯](dimmed white) "
    │            ^^ Icon 'nf-mdi-timer_sand' is marked as obsolete
    │
    = You could replace it with:
          1. 󰔟 U+F051F nf-md-timer_sand
          2. 󱦠 U+F19A0 nf-md-timer_sand_paused
          3. 󰞌 U+F078C nf-md-timer_sand_full
          4. 󰚭 U+F06AD nf-md-timer_sand_empty

> Input an icon: 󰔟
# Your input: 󰔟 nf-md-timer_sand
> Are your sure to write the patched content? all yes
```

The full file changes after the nerdfix command got executed can be found here:
https://github.com/jpcercal/dotfiles/commit/23898f0a110e4fcbe79da574a1d78526063f15fb

Reference:
https://github.com/loichyan/nerdfix

Thanks!

**Comment by Finii** [comment] 2024-03-30 11:33
I guess we can close this issue now. It will still be pinned for some time.

**Closed by Finii** 2024-03-30 11:33 UTC
Labels: confirmed, not-a-bug
