### ISSUE TITLE
after paching the comic code font using lualine the rounded powerline glyphs line hight is not showing properly

### ISSUE THREAD

**Issue by al3rez** [ryanoasis/nerd-fonts#1063] opened 2023-01-21 18:06 UTC
#### 🗹 Requirements

I've recently bought the Comic Code from myfonts and I decided to patch it using the docker and I ended up getting line breaks on Powerline gylyphs, I'm using lualine and Noevim.

Neovim + Lualine (Ecovim distro)
Mac M1
Comic Code Ligatures

#### 🎯 Subject of the issue
mis-aligned powerline glyphs

#### ★ Screenshots (Optional)

<img width="841" alt="Screen-Shot-2566-01-22-at-00 49 03" src="https://user-images.githubusercontent.com/15009059/213880393-5bcb6f83-16ad-4f72-81c7-ee65f7d6fa35.png">

**Comment by Finii** [comment] 2023-01-21 21:54
Sorry to hear of your problems. 
Thanks for reporting. 

I believe this will be fixed by #1060, expect to update the docker tomorrow. 



________________________________
From: Alireza Bashiri ***@***.***>
Sent: Saturday, 21 January 2023 19:06
To: ryanoasis/nerd-fonts
Cc: Subscribed
Subject: [ryanoasis/nerd-fonts] after paching the comic code font using lualine the rounded powerline glyphs line hight is not showing properly (Issue #1063)

🗹 Requirements
I've recently bought the Comic Code from myfonts and I decided to patch it using the docker and I ended up getting line breaks on Powerline gylyphs, I'm using lualine and Noevim.
Neovim + Lualine (Ecovim distro)
Mac M1
Comic Code Ligatures
🎯 Subject of the issue
mis-aligned powerline glyphs
★ Screenshots (Optional)

**Comment by Finii** [comment] 2023-01-22 18:45
#1060 has been pulled, docker updated.
Can you test if the problem is solved for you?

**Comment by al3rez** [comment] 2023-01-22 20:33
Works like a charm! 
<img width="2502" alt="Screen Shot 2566-01-23 at 03 32 42" src="https://user-images.githubusercontent.com/15009059/213938940-e8b0abb0-dbb9-4084-a245-c24b0c8bdf9f.png">

it look a bit thing but it's better than before

**Comment by al3rez** [comment] 2023-01-22 20:33
It works! 
<img width="352" alt="Screen Shot 2566-01-23 at 03 33 19" src="https://user-images.githubusercontent.com/15009059/213938961-f9d461a3-379e-4e2f-9109-49cff085b416.png">

**Comment by Finii** [comment] 2023-01-22 20:40
Thanks for testing :-)

Will release 2.3.2 soon.

**Closed by Finii** 2023-01-22 20:40 UTC
