### ISSUE TITLE
Weird lines and cutoff italics with JetBrains Mono

### ISSUE THREAD

**Issue by 257m** [ryanoasis/nerd-fonts#1355] opened 2023-09-25 18:15 UTC
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

I get lines in between character (for powerline icons) and cutoff icons and italics

Expected behavior:

I would have expected them to not have lines and cutoff icons. I think the lines are just the background color of the character so it might be anti aliasing issue. I have found some similar issues on here but I do not know how to patch my own font so I cannot use their solution.

Example symbols:

Mostly Powerline symbols having lines as well cutoff icons and italics

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - JetBrainsMonoNLNerdFontMono-Regular.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - I have tried both the github repository and a repository from pacman
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - xterm
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Linux - Endeavor Os

#### ★ Screenshots (Optional)

![2023-09-25-14:08:06-screenshot](https://github.com/ryanoasis/nerd-fonts/assets/107591653/4130622d-cdf8-48d1-97a5-d6eea574a5c6)
![2023-09-06-19:05:36-screenshot](https://github.com/ryanoasis/nerd-fonts/assets/107591653/9d8bbc56-e07c-4aa7-a6d6-f75be225b049)

**Comment by Finii** [comment] 2023-09-26 06:11
Sorry to hear of your problems.

The colored lines are artifacts produced by the antialiasing; if possible turn it to grayscale:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/80f6d751-2c40-4a9d-9484-0e8a60bd5ed9)
_Gnome tweak tool shown_

With contemporary resolutions I believe the LCD antialiasing is almost never an advantage anymore.
In principle we could produce slightly different Powerline glyphs that hide the problem better, but I believe while they improve the rendering with some clients other clients will get worse - so the current behavior is kind of a compromise.

The cut-off icons in the upper image should not occur if you use the `Nerd Font Mono` variant, I will check that.

I do not see any cut-off italics in your examples.

**Comment by Finii** [comment] 2023-09-26 06:52
You did not specify the codepoints of your broken icons (in the "example symbols" section), but when looking into the font I do not see anything that would produce your output.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/9f5dbadf-393f-4779-85d6-4fed42b797ca)
_Circle-with-x as wide as letter M, both one slot wide_

Maybe you selected a different font than specified in your description.

Trying ...

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/9a48a307-e024-45ef-a48e-3a27ad515d54)

Hmm :thinking:

**Comment by Finii** [comment] 2023-09-26 06:55
Ahh, I used the `Nerd Font (regular)` instead of the `Nerd Font Mono` ... correcting:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/0c1bf9b3-49e8-47f4-91a1-1bf07de4b06c)

Can not reproduce.

**Comment by Finii** [comment] 2023-09-26 06:58
Closing because I believe instead of the font you specify in the report:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/b2734842-9592-4be7-b9c8-55523a2a4096)

you do not use the `Nerd Font Mono` variant but the regular one. Please check your setup.
If you still have problems please reopen and post your setting etc.

**Closed by Finii** 2023-09-26 06:58 UTC
