### ISSUE TITLE
Line height went wrong after patching Comic Code

### ISSUE THREAD

**Issue by Mano-Liaoyan** [ryanoasis/nerd-fonts#1165] opened 2023-04-09 13:49 UTC
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

The line height is different after patching, but you can see longer characters display incorrectly

Expected behavior:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/43143420/230776451-379e5e1f-c2b6-42ea-beaf-f19c5e83a0e8.png">

Example symbols:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/43143420/230776369-1b7c9f6f-cb87-4067-b161-4b8411321cde.png">

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Comic Code Medium Nerd Font Complete.otf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Selfpatched from Comic Code Medium (which is a copyright font)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Windows Terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - WSL2

**Comment by Finii** [comment] 2023-04-09 16:36
Sorry to hear of your problem.

Maybe https://github.com/ryanoasis/nerd-fonts/issues/850#issuecomment-1500428279 can help you?

Which version of the patcher did you use (Nerd Fonts version number but more importantly the additional version in parens)?

Maybe we should add a commandline option to select one of the three different heights...

**Comment by Finii** [comment] 2023-04-09 16:37
Also compare
* https://github.com/ryanoasis/nerd-fonts/issues/1063

**Comment by Mano-Liaoyan** [comment] 2023-04-09 18:22
Thank you for your kind reply Finii! I've followed the instruction for font-line, however, even if I tuned the percent value to 1, it also shifts down a bit and makes the whole format look so tight.

Looks good in fontforge
<img width="500" alt="image" src="https://user-images.githubusercontent.com/43143420/230789434-a6e68f81-a44b-4e76-83a0-175617356b51.png">
But not in terminal
![ezgif com-gif-maker](https://user-images.githubusercontent.com/43143420/230789892-67421dac-8c5a-40e5-bac3-4cb53fb6eff5.gif)

In Windows:
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/43143420/230789550-df7219ef-287d-4c9b-802a-e720740eba40.png">
You can see the j and f are not shown correctly

I wonder if there are other solutions. Thx.

Btw, 
Nerd Fonts version: <img width="444" alt="image" src="https://user-images.githubusercontent.com/43143420/230789356-f82e518a-d671-4902-be62-7500d8262dc4.png">

**Comment by Finii** [comment] 2023-04-09 19:28
I have only the demo here... (also downloaded from myfonts)

![image](https://user-images.githubusercontent.com/16012374/230786947-ee095bd5-d179-41f6-ac1d-00c23e243e72.png)

The problem with this font is that it has 'contradicting' baseline to baseline distances encoded:

![image](https://user-images.githubusercontent.com/16012374/230787128-a603ccf9-84a4-41b2-924c-ebad0c444069.png)

The problem is in these metrixes

```
[OS/2] TypoAscender:   800
[OS/2] TypoDescender: -200
[OS/2] WinAscent:      1136
[OS/2] WinDescent:     331
[hhea] Ascent:         1136
[hhea] Descent:       -331

[hhea] LineGap:        200
[OS/2] TypoLineGap:    200
```

When I patch I get this output:

![image](https://user-images.githubusercontent.com/16012374/230787352-fcf9bcc0-162e-43c4-8674-136a06db026b.png)

---

Needed to help with one of my kids homework :grimacing: Let me examine your new comment...

**Comment by Finii** [comment] 2023-04-09 19:37
Oh, you use `v2.3.3 (3.5.1)`, but there is a bug exactly causing your problem that has been fixed with `3.5.7` see https://github.com/ryanoasis/nerd-fonts/issues/850#issuecomment-1431787822. Current is `3.6.1`.

![image](https://user-images.githubusercontent.com/16012374/230792961-43f18a67-a79c-478e-93b1-541a64cf0aa5.png)

**Comment by Mano-Liaoyan** [comment] 2023-04-09 19:38
Haha, have fun with your kids! It's not emergence here :) . I also get the warning that reminds the vertical metrics are not consistent,
<img width="947" alt="image" src="https://user-images.githubusercontent.com/43143420/230793041-ac8191d4-7f19-4a49-baae-6b3db2d676f8.png">
However, when I used the linegap version, the warning disappear,
<img width="796" alt="image" src="https://user-images.githubusercontent.com/43143420/230793065-cbc5e73f-e060-4769-9c43-9e9c5f4861a1.png">
If you don't mind, I can send an email to you that contains the font files

**Comment by Finii** [comment] 2023-04-09 19:41
This is the `font-patcher` version I use:

![image](https://user-images.githubusercontent.com/16012374/230793178-94cf13ce-31c3-40e8-9419-000a06fe0eef.png)

If you can update to at least `3.5.7` you should be able to patch yourself. If not, feel free to mail me the file(s) and I can patch them for you with `v2.3.3` style oder `v3.0.0` ;-D

**Comment by Finii** [comment] 2023-04-09 19:49
Btw, if you patch more than one font (e.g. Medium and Bold or Medium and Medium-Italic, or even more) you should add `--makegroups` to avoid the broken old naming scheme.

**Comment by Finii** [comment] 2023-04-09 20:06
You seem to not-use the docker image. Probably you use the zip file.
The up-to-date `master` zip is not on the Release page but here https://github.com/ryanoasis/nerd-fonts/blob/master/FontPatcher.zip

**Comment by Mano-Liaoyan** [comment] 2023-04-09 20:15
> You seem to not-use the docker image. Probably you use the zip file. The up-to-date `master` zip is not on the Release page but here https://github.com/ryanoasis/nerd-fonts/blob/master/FontPatcher.zip

Great! I have all the work done! Thanks a lot for your generous help!
<img width="1898" alt="image" src="https://user-images.githubusercontent.com/43143420/230794448-cdf37c4a-b71d-4b67-959e-7c12f05130c8.png">
All the icons are presented and fonts are correctly displayed! To you with all my sincere respect! Have a great day!

**Closed** 2023-04-10 10:19 UTC

**Comment by remiconnesson** [comment] 2023-08-19 13:44
@Mano-Liaoyan I have the same issue and I'm failing to understand how you've set the correct line height 

<img width="865" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/28846642/dd832d49-5204-452f-bf84-35c9ed1c9b54">

This is using the latest version of font-patcher

**Comment by Mano-Liaoyan** [comment] 2023-10-04 22:29
@remiconnesson Apologized for letting you wait for sooo long. I have not noticed this reply at all QAQ.

It seems that your command is different from mine.

![image](https://github.com/ryanoasis/nerd-fonts/assets/43143420/00bb8c2a-effd-4bde-938f-aeb3b7faa56e)

Maby you can try the script above?

```bash
fontforge font-patcher -wc --makegroups *.otf
```

**Comment by Finii** [comment] 2023-10-05 03:40
@remiconnesson 

Ah I see from the WARNING that there might be a problem with the metrics source in your case.
The PR
* #1300 

would enable you to patch the height as you want. Not sure why I did not pull that yet :thinking:

**Comment by Finii** [comment] 2023-10-05 03:46
Because the line height is not consistent in that ComicCode it depends on your platform which line height is displayed for the unpatched font. Nerd Fonts unifies the line height (it can not possibly work if the line height is unknown or can vary platform to platform), so it has to choose one.

Please ping me if #1300 is not pulled soon ;-) I might forget it.

Also if you specify `--debug 2` on your runs I will possibly more debug infos in your screenshots to work with.
