### ISSUE TITLE
Some fonts not rendering in native PowerShell but do in Terminal or VS Code.

### ISSUE THREAD

**Issue by FernandoBorea** [ryanoasis/nerd-fonts#698] opened 2021-11-29 18:00 UTC
#### 🎯 Subject of the issue

I recently installed the Caskaydia font, it worked perfectly with Oh My Posh and VS Code, but I just noticed some icons are not rendering when opening the native PowerShell app. Is this an issue or just a limitation of PowerShell?

#### 🔧 Your Setup

- Caskaydia Mono
- Windows Terminal, PowerShell and VS Code
- Windows 10

#### ★ Optional

![image](https://user-images.githubusercontent.com/36306738/143919228-afad3a7f-7d6e-44dd-b3ee-82e76c5b9f9e.png)

![image](https://user-images.githubusercontent.com/36306738/143919254-d703a2ff-d209-4169-ade2-bdf792c277dd.png)

![image](https://user-images.githubusercontent.com/36306738/143919311-e802a869-0273-454e-9068-d1451caeaa0a.png)

**Comment by Finii** [comment] 2021-11-30 07:12
Can you copy & paste the relevant icons into a comment _as text_? Or give the unicode for them? In that way I could try to reproduce. Best would be to textual copy&paste the complete two prompt-lines.

Good would also be to include the open font selection dialog in the screenshots of the shells ;-)

**Comment by FernandoBorea** [comment] 2021-12-10 23:36
Hey!

I apologize for the delay, I missed the thread reply notification. Here's the info:

Windows Terminal (works just fine):
╭─    ~                                                                                        ✔  17:34:07  ─╮
╰─🦄                                                                                                                 ─╯

![image](https://user-images.githubusercontent.com/36306738/145653945-ff2015a7-d0f8-4a73-9d41-edaf7954cefe.png)

Powershell (doesn't render the curves characters):
╭─    C:\Windows\System32                                                                      ✔  17:35:32  ─╮
╰─🦄                                                                                                                 ─╯

![image](https://user-images.githubusercontent.com/36306738/145654019-2db67687-256e-4fb3-83a2-9c69ad7bde2b.png)

**Comment by Finii** [comment] 2021-12-11 10:49
Thank you, will investigate.

**Comment by FernandoBorea** [comment] 2021-12-14 02:50
Thanks! Will keep an eye:)

**Comment by Finii** [comment] 2021-12-14 06:35
Curvy upwards: `╭` `u_256d` _Box drawing light arc down and right_
Line: `─` `u_2500` _Box drawing light horizontal_

Seem to be included:
![image](https://user-images.githubusercontent.com/16012374/145945725-adda7084-3ab4-4462-bae9-c8a352e6856f.png)

Booting up the Windows box...

**Comment by Finii** [comment] 2021-12-14 06:43
Just copy&pasted the upper line (i.e.  ╭─    C:\Windows\System32   heavy_check_mark  17:35:32  ─╮) and it seems to show:
![image](https://user-images.githubusercontent.com/16012374/145946417-9de90c00-9070-4e36-b355-a6d509ceaf47.png)

As you see some chars are suppressed when one types them in, but they show in the error message.

Need to find out how to set a prompt :-> (But I think the font rendering is ok, this is a PowerShell intrinsic special behavior)

**Comment by Finii** [comment] 2021-12-14 06:50
In fact that was **Consolas**.

I can not select **Caskaydia Cove NF Complete WIN** in PowerShell, probably because Panose is missing :->

**Comment by Finii** [comment] 2021-12-14 07:00
Can see the symbols with a Panose corrected Caskaydia.

![image](https://user-images.githubusercontent.com/16012374/145948292-a864caea-6653-4d7f-91e8-76c05ecf0e16.png)

How comes that you can select Caskaydia in PowerShell while I cannot? I tried this directly out of the repos `patched_fonts/`:
![image](https://user-images.githubusercontent.com/16012374/145948619-ee3b8673-ec59-493d-b4a7-a75cba19ab9f.png)

**Comment by Finii** [comment] 2021-12-14 07:07
Prompt works:
![image](https://user-images.githubusercontent.com/16012374/145949221-931f8c75-6fd8-469c-aa7d-047724393f47.png)

This leaves the questions
* How are you able to select Caskaydia? (Please show screenshot incl whole PS windows and it's font chooser dialogue)
* Where exactly originates the font you installed?
* Please try the copy and paste dance I used ;) Maybe something with the Powerline setup is broken

**Comment by Finii** [comment] 2021-12-23 06:45
This will be fixed once the patched fonts are all regenerated.
Self patching with HEAD would also work.

I close this now, reopen if you need further help.

**Closed by Finii** 2021-12-23 06:45 UTC
