### ISSUE TITLE
Overpass Nerdfont kerning is incorrect

### ISSUE THREAD

**Issue by InfoSec812** [ryanoasis/nerd-fonts#703] opened 2021-12-03 18:44 UTC
#### 🗹 Requirements

- [ ] A brief but descriptive _title_ of your issue
- [ ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [ ] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ ] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Spacing issues in Overpass Nerdfont

When I use Overpass Nerdfont the spacing between letters is mishandled.

![image](https://user-images.githubusercontent.com/99691/144656035-761f1f72-db04-4151-8c61-dd81ea8047f1.png)

#### 🔧 Your Setup

- Overpass Nerdfont Mono
- It happens in all of them on Linux as well as in my IDEs
- Linux

**Comment by ryanoasis** [comment] 2021-12-20 16:18
It's strange because even the unpatched Overpass is displaying strangely in gnome terminal for me just like your screenshot.

![Selection_097](https://user-images.githubusercontent.com/8083459/146798792-96dbcf50-010d-4a2d-8e17-ddfcf1b96741.png)

However something like gedit both patched and unpatched Overpass look fine 🤔 

![Selection_098](https://user-images.githubusercontent.com/8083459/146798767-f2414230-c9dc-4bf5-8977-ed7f67ecab0f.png)

**Comment by InfoSec812** [comment] 2021-12-21 17:34
Hmmm. I have no issues with the unpatched Overpass Mono from Google Fonts. Also, I have issues with the patched version in EVERY application, not just Gnome terminal.

**Comment by InfoSec812** [comment] 2021-12-21 17:42
Example:

Konsole with Overpass Mono (unpatched)
![image](https://user-images.githubusercontent.com/99691/146974444-76094e9f-1eae-4a52-a0e5-df1850bc5b46.png)

Konsole with Overpass Mono (patched)
![image](https://user-images.githubusercontent.com/99691/146974487-b83707d9-2b00-4fef-818b-456795bad698.png)

**Comment by Finii** [comment] 2021-12-21 19:36
Hmm, dowloaded Overpass-Mono from G-Fonts and patched with HEAD. Shows ok in Tilix.

![image](https://user-images.githubusercontent.com/16012374/146987128-f8e2c049-ac55-459c-a6d1-e426b6d2afe3.png)


I can not, however, select it with Gnome Terminal. But it (Terminal) looks different to yours:

![image](https://user-images.githubusercontent.com/16012374/146987285-d7b50c77-cbe0-49a0-b646-b9f97f6ac185.png)

But then, no wonder:
```shell
$ ttfdump Overpass\ Mono\ Regular\ Nerd\ Font\ Complete\ Mono.ttf  | grep 'advanceWidthMa|maxCompositePoin|xAvgCharWi'
	 advanceWidthMax:	        1517
	 maxCompositePoints:	 94
	 xAvgCharWidth:		 1232
```

**Comment by Finii** [comment] 2021-12-21 22:01
Well ... if I use a `font-patcher` where the `ScaleGlyph` stuff is fixed (i.e. what I work on at the bottom of #695), it shows up in my Gnome Terminal and looks good.

![image](https://user-images.githubusercontent.com/16012374/147002511-3ac30af8-d4c4-469f-8e5e-8b61d02108e7.png)

This does not mean the patch of #695, but this unpushed stuff:

```
CommitDate: Mon Dec 20 14:57:56 2021 +0100

    font-patcher: Redesign ScaleGlyph parameter

    [why]
    While patching for --mono with Font Awesome we get glyphs that are
    too wide, for example '_520' (0xF22B). In the symbol font original
    it is about 1918 wide. According to ScaleGlyph FONTA_SCALE_LIST
    it shall be scaled as 0xF17A - which is only 1664 wide.

    This results in too wide symbols in the patched font.
```

If you want to try, just set all `*_SCALE_LIST` to None. Well, the symbol sizes will be non-optimal, but the font otherwise will be real 'Mono'. The commit is a bit more complex and I'm still undecided which stategy of two I prepared is better.

**Comment by Finii** [comment] 2023-01-06 15:29
This is fixed in `2.2.2`
Note that we use the `otf` instead of `ttf` now.

```
$ ttfdump Overpass\ Mono\ Regular\ Nerd\ Font\ Complete\ Mono.otf  \
| grep 'advanceWidthMa|maxCompositePoin|xAvgCharWi'
	 advanceWidthMax:	 1232
	 maxCompositePoints:	 1232
	 xAvgCharWidth:		 1232
```

All widths consistent.

**Comment by luciodaou** [comment] 2023-01-20 23:29
I'm having this issue on Overpass-Mono-NF 2.3.1 installed through scoop on Win11:
![image](https://user-images.githubusercontent.com/53634214/213822685-9205f2c4-1f7c-4038-a612-7bd69e5a2d4d.png)

Windows Font says 2.3.0, somehow.
![image](https://user-images.githubusercontent.com/53634214/213822696-fc19c73e-58d9-4a7b-8fe3-3b814977cf43.png)

The issue happens with the file downloaded from directly from GitHub too:
https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Overpass/Mono/Regular/complete/Overpass%20Mono%20Regular%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.otf

**Comment by Finii** [comment] 2023-01-21 10:28
Sorry to hear that you have problems, will have a look right away.

The v2.3.1 is actually marked in the font files as v2.3.0 because only very few font files got any change with the bugfix version, and it was clear to me we will need a 2.3.2 anyhow ;)

**Comment by Finii** [comment] 2023-01-21 10:33
Confirmed.
I really need to implement a warning for unexpected widths. Thanks for reporting!

**Closed** 2023-01-22 14:08 UTC
Labels: ⚠ bug
