### ISSUE TITLE
Glyph codepoints in complete NerdFonts glyphs TTF files fall out of the Unicode PUA

### ISSUE THREAD

**Issue by bool3max** [ryanoasis/nerd-fonts#560] opened 2021-01-12 16:42 UTC
I am using the Arch linux pacakge [ttf-nerd-fonts-symbols-mono](https://archlinux.org/packages/community/x86_64/ttf-nerd-fonts-symbols-mono/). 

The files (in `src/glyphs/`): 

* Symbols-2048-em Nerd Font Complete.ttf
* Symbols-1000-em Nerd Font Complete.ttf

contain glyphs whose codepoints fall out of the PUA. 

An example is the Amazon logo symbol which is mapped to **U+FBD9**, which is not within the PUA, but rather belongs to  *Arabic Presentation Forms-A, U+FB50 to U+FDFF*.

---

As I am fairly new to NerdFonts, I am unsure whether this is intended (and the codepoints are re-arranged once the fonts are patched using a script - resulting in this being the mistake of the arch package maintainer providing this package as a standalone in the first place), or whether this is a mistake on nerd-fonts' part.

**Comment by polyzen** [comment] 2021-01-12 16:57
Duplicate of #365

**Closed** 2021-01-12 17:03 UTC
