### ISSUE TITLE
Add support for recursive font

### ISSUE THREAD

**Issue by Aerma7309** [ryanoasis/nerd-fonts#1523] opened 2024-02-24 08:08 UTC
**Requirements**

Recursive font is gaining a lot of popularity, we need to patch that too.

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Want recursive font patched and included in upcoming releases. 

**Describe alternatives you've considered**

**Additional context**
Recursive Font Repo : [https://github.com/arrowtype/recursive](https://github.com/arrowtype/recursive)

**Comment by Finii** [comment] 2024-02-24 08:27
> [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful

Duplicate of #845

**Closed by Finii** 2024-02-24 08:27 UTC
