### ISSUE TITLE
Add IBM Plex Mono `otf` 

### ISSUE THREAD

**Issue by ZorinFoss** [ryanoasis/nerd-fonts#1699] opened 2024-08-31 05:39 UTC
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

IBM Plex Mono `ttf` version render light

### Desired Solution

Please add IBM Plex Mono `otf` version because it render better than `ttf`

Thanks,

### Alternatives Considered

Add IBM Plex Mono `otf` version

**Comment by Finii** [comment] 2024-08-31 14:14
Any explanation why you closed this? Not that I could have done much about it.

And then I checked the IBM Plex repo, and they had a new release yesterday :tada: 

Version 1.0

WHAT? We have Version 2.004 from Release 6.4.0 ... 

Ah, they just started again counting from one, probably when switching to monorepo.
But the font is still 2.004 :sweat: 

Old wine in new skins :grimacing: 

Ah, no, they added **telemetry**, thank god! :tada: Of course what we all need!

**Comment by Finii** [comment] 2024-08-31 14:16
> IBM Telemetry gets installed too and runs a script which analyzes your source code and captures data

Analyzes my code? (O_o)

**Comment by ZorinFoss** [comment] 2024-08-31 18:13
I just try to patch new fonts and it worked well. `otf` version is rendering better than `ttf`.

**Comment by Finii** [comment] 2024-09-01 16:12
> patch new fonts

There are no new fonts `IBM Plex Mono`. Its the same old font we have here, just with a new release tag that means nothing.

As for `otf` vs `ttf`
* Can you provide screenshots and a textual description what is better with the `otf`s?
* Which OS are you using? Possibly which application?

The version you download here is `ttf`, this is the `normal` one. If you prefer the `otf` that might be a personal decision? If we would switch all Nerd Fonts update will break, that is not really a desirable thing to do.

Uses ttf: https://www.ibm.com/plex (the website itself for the previews)
Uses ttf: https://fonts.google.com/specimen/IBM+Plex+Mono (when dowloaded from here)

So I's dare say what the font designers inteded is the `ttf` look. If there are differences (depending on your OS, see question above) that might be because of the different hinting for ttf and otf and most probably otf is not hand optimized (guessing).

**Comment by ZorinFoss** [comment] 2024-09-01 17:19
> There are no new fonts IBM Plex Mono. Its the same old font we have here, just with a new release tag that means nothing.
i was mean new release of `otf IBM Plex Mono` 

`otf` *screenshot from KDE Plasma Konsol* 
![Screenshot_20240901_201150](https://github.com/user-attachments/assets/e0723949-8ddb-4a1c-b135-689e80ea1a85)

`ttf` *screenshot from KDE Plasma Konsol*
![Screenshot_20240901_200827](https://github.com/user-attachments/assets/67d76fa1-8fd5-4c5f-836a-e82084045798)

- If it possible to add just `otf IBM Plex Mono` it will be great.

**Comment by Finii** [comment] 2024-09-02 09:16
Your screenshots at 400%

![image](https://github.com/user-attachments/assets/7c3a4101-c4de-44c4-824a-b1949bf9b972)
_Upper: otf, lower: ttf_

The lower variant ('ttf') looks less heavy.

Lets try to reproduce:

![image](https://github.com/user-attachments/assets/e6301c32-5f32-4057-90dd-427a9fefa594)

![image](https://github.com/user-attachments/assets/73233d8a-38d1-4087-a6f0-7a71a10a37ba)

Hmm, I can not really see a difference; I could imagine one, but not as vast as in your images:

![image](https://github.com/user-attachments/assets/d5f85c10-2d92-4055-aef1-45770ff47da7)

_Upper: otf, lower: ttf_

I guess there is either something wrong with your Wayland setup or with your subpixel-rendering settings.
Plasma is just using Wayland (or X86) under the hood, I assume?

My screenshots are from a Gnome on Wayland system, with these settings:

![image](https://github.com/user-attachments/assets/14ca5db3-aa69-4ecb-bd88-024e033a534f)

**Comment by ZorinFoss** [comment] 2024-09-07 04:18
This is not wayland issue. the same behaviour also happen on X11 and on old plasma 5 versions.

**Comment by Finii** [comment] 2024-11-20 13:09
Well, I think we will not add another format of one font. We had some of this (one font both `ttf` and `otf` in the release), but that has been removed to have a simpler setup and usually `ttf` has more OpenType possibilities that `otf`, that is why we normally prefer `ttf`.

The concrete font's main format is also `ttf` and we should probably stick to it. The fact that the `otf` looks different is in fact an unwanted artefact.

**Closed by Finii** 2024-11-20 13:09 UTC
Labels: unreproducible
